/**
 * Complete Team Foul Game Data
 * Based on analysis of 3,649 games (1,237 with foul game situations)
 * Generated from S3 play-by-play data
 *
 * Data for 359 NCAA teams
 */

export interface TeamFoulGameData {
  timesFouling: number;       // Games where team was trailing and fouled
  timesLeading: number;       // Games where team was leading and got fouled
  totalGames: number;         // Total foul game involvement
  avgStartClock: number;      // Avg seconds remaining when they start fouling
  avgDeficit: number;         // Avg point deficit when they foul
  avgExtraPtsFouling: number; // Avg extra points when fouling (trailing)
  avgExtraPtsLeading: number; // Avg extra points when leading (being fouled)
}

// All teams with foul game data
export const TEAM_FOUL_GAME_DATA: Record<string, TeamFoulGameData> = {
  "Charlotte 49ers": {
    timesFouling: 6,
    timesLeading: 7,
    totalGames: 13,
    avgStartClock: 111.0,
    avgDeficit: 7.7,
    avgExtraPtsFouling: 7.6,
    avgExtraPtsLeading: 5.0,
  },
  "Northeastern Huskies": {
    timesFouling: 10,
    timesLeading: 3,
    totalGames: 13,
    avgStartClock: 111.3,
    avgDeficit: 6.2,
    avgExtraPtsFouling: 4.0,
    avgExtraPtsLeading: 0.8,
  },
  "Jacksonville State Gamecocks": {
    timesFouling: 6,
    timesLeading: 7,
    totalGames: 13,
    avgStartClock: 110.5,
    avgDeficit: 4.3,
    avgExtraPtsFouling: 4.9,
    avgExtraPtsLeading: 8.2,
  },
  "Hofstra Pride": {
    timesFouling: 6,
    timesLeading: 6,
    totalGames: 12,
    avgStartClock: 110.0,
    avgDeficit: 6.2,
    avgExtraPtsFouling: 8.1,
    avgExtraPtsLeading: 3.0,
  },
  "Mount St. Mary's Mountaineers": {
    timesFouling: 7,
    timesLeading: 5,
    totalGames: 12,
    avgStartClock: 108.4,
    avgDeficit: 5.9,
    avgExtraPtsFouling: 7.2,
    avgExtraPtsLeading: 6.5,
  },
  "Merrimack Warriors": {
    timesFouling: 3,
    timesLeading: 9,
    totalGames: 12,
    avgStartClock: 104.0,
    avgDeficit: 4.7,
    avgExtraPtsFouling: 7.7,
    avgExtraPtsLeading: 6.1,
  },
  "Vermont Catamounts": {
    timesFouling: 6,
    timesLeading: 6,
    totalGames: 12,
    avgStartClock: 110.7,
    avgDeficit: 4.3,
    avgExtraPtsFouling: 5.4,
    avgExtraPtsLeading: 6.1,
  },
  "Kent State Golden Flashes": {
    timesFouling: 2,
    timesLeading: 10,
    totalGames: 12,
    avgStartClock: 118.5,
    avgDeficit: 5.0,
    avgExtraPtsFouling: 5.8,
    avgExtraPtsLeading: 6.5,
  },
  "Massachusetts Minutemen": {
    timesFouling: 6,
    timesLeading: 5,
    totalGames: 11,
    avgStartClock: 112.2,
    avgDeficit: 3.7,
    avgExtraPtsFouling: 3.8,
    avgExtraPtsLeading: 4.9,
  },
  "Austin Peay Governors": {
    timesFouling: 5,
    timesLeading: 6,
    totalGames: 11,
    avgStartClock: 115.6,
    avgDeficit: 6.8,
    avgExtraPtsFouling: 3.0,
    avgExtraPtsLeading: 2.6,
  },
  "St. Bonaventure Bonnies": {
    timesFouling: 4,
    timesLeading: 7,
    totalGames: 11,
    avgStartClock: 108.2,
    avgDeficit: 4.0,
    avgExtraPtsFouling: 8.8,
    avgExtraPtsLeading: 5.5,
  },
  "Wofford Terriers": {
    timesFouling: 4,
    timesLeading: 7,
    totalGames: 11,
    avgStartClock: 110.2,
    avgDeficit: 6.0,
    avgExtraPtsFouling: 5.5,
    avgExtraPtsLeading: 7.9,
  },
  "Montana State Bobcats": {
    timesFouling: 4,
    timesLeading: 7,
    totalGames: 11,
    avgStartClock: 98.8,
    avgDeficit: 4.2,
    avgExtraPtsFouling: 6.5,
    avgExtraPtsLeading: 7.7,
  },
  "Charleston Cougars": {
    timesFouling: 5,
    timesLeading: 6,
    totalGames: 11,
    avgStartClock: 103.2,
    avgDeficit: 6.4,
    avgExtraPtsFouling: 3.6,
    avgExtraPtsLeading: 4.8,
  },
  "Colorado Buffaloes": {
    timesFouling: 2,
    timesLeading: 9,
    totalGames: 11,
    avgStartClock: 111.5,
    avgDeficit: 8.5,
    avgExtraPtsFouling: 9.9,
    avgExtraPtsLeading: 6.8,
  },
  "Bradley Braves": {
    timesFouling: 4,
    timesLeading: 7,
    totalGames: 11,
    avgStartClock: 107.8,
    avgDeficit: 3.2,
    avgExtraPtsFouling: 3.9,
    avgExtraPtsLeading: 2.8,
  },
  "Oregon State Beavers": {
    timesFouling: 5,
    timesLeading: 6,
    totalGames: 11,
    avgStartClock: 109.4,
    avgDeficit: 6.8,
    avgExtraPtsFouling: 7.4,
    avgExtraPtsLeading: 3.5,
  },
  "Valparaiso Beacons": {
    timesFouling: 5,
    timesLeading: 6,
    totalGames: 11,
    avgStartClock: 112.4,
    avgDeficit: 5.6,
    avgExtraPtsFouling: 6.3,
    avgExtraPtsLeading: 5.0,
  },
  "San Francisco Dons": {
    timesFouling: 4,
    timesLeading: 7,
    totalGames: 11,
    avgStartClock: 102.2,
    avgDeficit: 4.5,
    avgExtraPtsFouling: 2.9,
    avgExtraPtsLeading: 6.7,
  },
  "Marshall Thundering Herd": {
    timesFouling: 2,
    timesLeading: 9,
    totalGames: 11,
    avgStartClock: 107.5,
    avgDeficit: 4.0,
    avgExtraPtsFouling: 3.8,
    avgExtraPtsLeading: 5.6,
  },
  "Colgate Raiders": {
    timesFouling: 3,
    timesLeading: 8,
    totalGames: 11,
    avgStartClock: 110.7,
    avgDeficit: 5.3,
    avgExtraPtsFouling: 4.0,
    avgExtraPtsLeading: 6.2,
  },
  "Army Black Knights": {
    timesFouling: 6,
    timesLeading: 5,
    totalGames: 11,
    avgStartClock: 93.3,
    avgDeficit: 7.5,
    avgExtraPtsFouling: 5.1,
    avgExtraPtsLeading: 6.9,
  },
  "California Baptist Lancers": {
    timesFouling: 5,
    timesLeading: 6,
    totalGames: 11,
    avgStartClock: 108.4,
    avgDeficit: 4.8,
    avgExtraPtsFouling: 4.7,
    avgExtraPtsLeading: 4.0,
  },
  "Coastal Carolina Chanticleers": {
    timesFouling: 5,
    timesLeading: 6,
    totalGames: 11,
    avgStartClock: 116.8,
    avgDeficit: 5.0,
    avgExtraPtsFouling: 7.8,
    avgExtraPtsLeading: 5.0,
  },
  "Princeton Tigers": {
    timesFouling: 4,
    timesLeading: 6,
    totalGames: 10,
    avgStartClock: 117.2,
    avgDeficit: 6.2,
    avgExtraPtsFouling: 6.2,
    avgExtraPtsLeading: 5.6,
  },
  "Louisiana Ragin' Cajuns": {
    timesFouling: 7,
    timesLeading: 3,
    totalGames: 10,
    avgStartClock: 111.7,
    avgDeficit: 6.9,
    avgExtraPtsFouling: 7.8,
    avgExtraPtsLeading: 4.4,
  },
  "Green Bay Phoenix": {
    timesFouling: 3,
    timesLeading: 7,
    totalGames: 10,
    avgStartClock: 102.7,
    avgDeficit: 6.3,
    avgExtraPtsFouling: 5.1,
    avgExtraPtsLeading: 6.1,
  },
  "Cal Poly Mustangs": {
    timesFouling: 5,
    timesLeading: 5,
    totalGames: 10,
    avgStartClock: 115.0,
    avgDeficit: 5.2,
    avgExtraPtsFouling: 7.1,
    avgExtraPtsLeading: 7.1,
  },
  "Idaho Vandals": {
    timesFouling: 6,
    timesLeading: 4,
    totalGames: 10,
    avgStartClock: 110.7,
    avgDeficit: 2.8,
    avgExtraPtsFouling: 4.7,
    avgExtraPtsLeading: 4.6,
  },
  "Bucknell Bison": {
    timesFouling: 5,
    timesLeading: 5,
    totalGames: 10,
    avgStartClock: 116.0,
    avgDeficit: 5.6,
    avgExtraPtsFouling: 8.4,
    avgExtraPtsLeading: 4.4,
  },
  "Stony Brook Seawolves": {
    timesFouling: 3,
    timesLeading: 7,
    totalGames: 10,
    avgStartClock: 111.3,
    avgDeficit: 6.3,
    avgExtraPtsFouling: 6.1,
    avgExtraPtsLeading: 7.8,
  },
  "Longwood Lancers": {
    timesFouling: 3,
    timesLeading: 7,
    totalGames: 10,
    avgStartClock: 84.7,
    avgDeficit: 5.0,
    avgExtraPtsFouling: 7.1,
    avgExtraPtsLeading: 6.0,
  },
  "Washington State Cougars": {
    timesFouling: 4,
    timesLeading: 6,
    totalGames: 10,
    avgStartClock: 71.5,
    avgDeficit: 7.5,
    avgExtraPtsFouling: 5.3,
    avgExtraPtsLeading: 5.7,
  },
  "Indiana State Sycamores": {
    timesFouling: 5,
    timesLeading: 5,
    totalGames: 10,
    avgStartClock: 112.8,
    avgDeficit: 4.0,
    avgExtraPtsFouling: 4.6,
    avgExtraPtsLeading: 3.7,
  },
  "Weber State Wildcats": {
    timesFouling: 5,
    timesLeading: 5,
    totalGames: 10,
    avgStartClock: 100.6,
    avgDeficit: 4.8,
    avgExtraPtsFouling: 6.8,
    avgExtraPtsLeading: 3.5,
  },
  "Portland Pilots": {
    timesFouling: 6,
    timesLeading: 4,
    totalGames: 10,
    avgStartClock: 105.3,
    avgDeficit: 5.5,
    avgExtraPtsFouling: 8.4,
    avgExtraPtsLeading: 5.3,
  },
  "Utah Utes": {
    timesFouling: 5,
    timesLeading: 5,
    totalGames: 10,
    avgStartClock: 100.4,
    avgDeficit: 6.6,
    avgExtraPtsFouling: 5.4,
    avgExtraPtsLeading: 7.8,
  },
  "Syracuse Orange": {
    timesFouling: 5,
    timesLeading: 5,
    totalGames: 10,
    avgStartClock: 112.6,
    avgDeficit: 5.6,
    avgExtraPtsFouling: 3.3,
    avgExtraPtsLeading: 5.5,
  },
  "Richmond Spiders": {
    timesFouling: 3,
    timesLeading: 7,
    totalGames: 10,
    avgStartClock: 115.0,
    avgDeficit: 4.3,
    avgExtraPtsFouling: 6.5,
    avgExtraPtsLeading: 10.4,
  },
  "Howard Bison": {
    timesFouling: 4,
    timesLeading: 5,
    totalGames: 9,
    avgStartClock: 118.5,
    avgDeficit: 5.5,
    avgExtraPtsFouling: 4.6,
    avgExtraPtsLeading: 14.1,
  },
  "Clemson Tigers": {
    timesFouling: 1,
    timesLeading: 8,
    totalGames: 9,
    avgStartClock: 98.0,
    avgDeficit: 3.0,
    avgExtraPtsFouling: 0.0,
    avgExtraPtsLeading: 4.9,
  },
  "Fresno State Bulldogs": {
    timesFouling: 5,
    timesLeading: 4,
    totalGames: 9,
    avgStartClock: 87.4,
    avgDeficit: 4.8,
    avgExtraPtsFouling: 1.8,
    avgExtraPtsLeading: 5.9,
  },
  "Elon Phoenix": {
    timesFouling: 6,
    timesLeading: 3,
    totalGames: 9,
    avgStartClock: 118.0,
    avgDeficit: 5.3,
    avgExtraPtsFouling: 6.8,
    avgExtraPtsLeading: 5.4,
  },
  "Cal State Northridge Matadors": {
    timesFouling: 4,
    timesLeading: 5,
    totalGames: 9,
    avgStartClock: 107.8,
    avgDeficit: 6.2,
    avgExtraPtsFouling: 3.8,
    avgExtraPtsLeading: 3.7,
  },
  "IU Indianapolis Jaguars": {
    timesFouling: 5,
    timesLeading: 4,
    totalGames: 9,
    avgStartClock: 111.6,
    avgDeficit: 7.4,
    avgExtraPtsFouling: 5.1,
    avgExtraPtsLeading: 5.5,
  },
  "UNC Wilmington Seahawks": {
    timesFouling: 2,
    timesLeading: 7,
    totalGames: 9,
    avgStartClock: 107.0,
    avgDeficit: 5.5,
    avgExtraPtsFouling: 4.8,
    avgExtraPtsLeading: 4.3,
  },
  "Omaha Mavericks": {
    timesFouling: 2,
    timesLeading: 7,
    totalGames: 9,
    avgStartClock: 115.5,
    avgDeficit: 3.5,
    avgExtraPtsFouling: 3.2,
    avgExtraPtsLeading: 3.2,
  },
  "Drake Bulldogs": {
    timesFouling: 5,
    timesLeading: 4,
    totalGames: 9,
    avgStartClock: 100.0,
    avgDeficit: 7.2,
    avgExtraPtsFouling: 9.5,
    avgExtraPtsLeading: 3.4,
  },
  "Buffalo Bulls": {
    timesFouling: 4,
    timesLeading: 5,
    totalGames: 9,
    avgStartClock: 111.5,
    avgDeficit: 6.2,
    avgExtraPtsFouling: 9.5,
    avgExtraPtsLeading: 6.0,
  },
  "Lipscomb Bisons": {
    timesFouling: 3,
    timesLeading: 6,
    totalGames: 9,
    avgStartClock: 97.0,
    avgDeficit: 5.7,
    avgExtraPtsFouling: 12.7,
    avgExtraPtsLeading: 5.6,
  },
  "Cal State Bakersfield Roadrunners": {
    timesFouling: 6,
    timesLeading: 3,
    totalGames: 9,
    avgStartClock: 82.5,
    avgDeficit: 7.2,
    avgExtraPtsFouling: 5.6,
    avgExtraPtsLeading: 2.7,
  },
  "Portland State Vikings": {
    timesFouling: 4,
    timesLeading: 5,
    totalGames: 9,
    avgStartClock: 112.8,
    avgDeficit: 7.5,
    avgExtraPtsFouling: 5.0,
    avgExtraPtsLeading: 5.9,
  },
  "Stanford Cardinal": {
    timesFouling: 4,
    timesLeading: 5,
    totalGames: 9,
    avgStartClock: 111.8,
    avgDeficit: 3.2,
    avgExtraPtsFouling: 5.6,
    avgExtraPtsLeading: 6.2,
  },
  "Western Illinois Leathernecks": {
    timesFouling: 8,
    timesLeading: 1,
    totalGames: 9,
    avgStartClock: 112.4,
    avgDeficit: 4.8,
    avgExtraPtsFouling: 5.0,
    avgExtraPtsLeading: 2.5,
  },
  "Northern Iowa Panthers": {
    timesFouling: 3,
    timesLeading: 6,
    totalGames: 9,
    avgStartClock: 112.3,
    avgDeficit: 4.7,
    avgExtraPtsFouling: 3.2,
    avgExtraPtsLeading: 4.3,
  },
  "TCU Horned Frogs": {
    timesFouling: 6,
    timesLeading: 3,
    totalGames: 9,
    avgStartClock: 107.0,
    avgDeficit: 5.0,
    avgExtraPtsFouling: 6.1,
    avgExtraPtsLeading: 2.0,
  },
  "Wright State Raiders": {
    timesFouling: 5,
    timesLeading: 4,
    totalGames: 9,
    avgStartClock: 95.4,
    avgDeficit: 3.6,
    avgExtraPtsFouling: 3.9,
    avgExtraPtsLeading: 5.6,
  },
  "DePaul Blue Demons": {
    timesFouling: 2,
    timesLeading: 7,
    totalGames: 9,
    avgStartClock: 115.5,
    avgDeficit: 7.5,
    avgExtraPtsFouling: 2.8,
    avgExtraPtsLeading: 4.4,
  },
  "Charleston Southern Buccaneers": {
    timesFouling: 5,
    timesLeading: 4,
    totalGames: 9,
    avgStartClock: 109.8,
    avgDeficit: 2.0,
    avgExtraPtsFouling: 4.5,
    avgExtraPtsLeading: 9.6,
  },
  "Old Dominion Monarchs": {
    timesFouling: 5,
    timesLeading: 4,
    totalGames: 9,
    avgStartClock: 96.0,
    avgDeficit: 5.6,
    avgExtraPtsFouling: 9.6,
    avgExtraPtsLeading: 9.1,
  },
  "UC Santa Barbara Gauchos": {
    timesFouling: 5,
    timesLeading: 4,
    totalGames: 9,
    avgStartClock: 105.4,
    avgDeficit: 6.0,
    avgExtraPtsFouling: 4.6,
    avgExtraPtsLeading: 7.2,
  },
  "Nevada Wolf Pack": {
    timesFouling: 3,
    timesLeading: 6,
    totalGames: 9,
    avgStartClock: 88.0,
    avgDeficit: 1.7,
    avgExtraPtsFouling: 6.5,
    avgExtraPtsLeading: 4.5,
  },
  "Radford Highlanders": {
    timesFouling: 5,
    timesLeading: 4,
    totalGames: 9,
    avgStartClock: 94.8,
    avgDeficit: 7.6,
    avgExtraPtsFouling: 9.5,
    avgExtraPtsLeading: 8.4,
  },
  "Manhattan Jaspers": {
    timesFouling: 5,
    timesLeading: 4,
    totalGames: 9,
    avgStartClock: 105.6,
    avgDeficit: 4.4,
    avgExtraPtsFouling: 4.3,
    avgExtraPtsLeading: 7.1,
  },
  "Robert Morris Colonials": {
    timesFouling: 3,
    timesLeading: 6,
    totalGames: 9,
    avgStartClock: 114.3,
    avgDeficit: 4.0,
    avgExtraPtsFouling: 4.8,
    avgExtraPtsLeading: 6.6,
  },
  "Eastern Washington Eagles": {
    timesFouling: 8,
    timesLeading: 1,
    totalGames: 9,
    avgStartClock: 89.4,
    avgDeficit: 7.2,
    avgExtraPtsFouling: 5.1,
    avgExtraPtsLeading: 13.1,
  },
  "Fairleigh Dickinson Knights": {
    timesFouling: 7,
    timesLeading: 2,
    totalGames: 9,
    avgStartClock: 115.9,
    avgDeficit: 6.3,
    avgExtraPtsFouling: 6.4,
    avgExtraPtsLeading: 7.3,
  },
  "Iona Gaels": {
    timesFouling: 4,
    timesLeading: 5,
    totalGames: 9,
    avgStartClock: 114.2,
    avgDeficit: 4.2,
    avgExtraPtsFouling: 4.3,
    avgExtraPtsLeading: 3.7,
  },
  "Loyola Chicago Ramblers": {
    timesFouling: 3,
    timesLeading: 6,
    totalGames: 9,
    avgStartClock: 95.0,
    avgDeficit: 7.3,
    avgExtraPtsFouling: 10.5,
    avgExtraPtsLeading: 3.9,
  },
  "SIU Edwardsville Cougars": {
    timesFouling: 5,
    timesLeading: 4,
    totalGames: 9,
    avgStartClock: 106.6,
    avgDeficit: 4.8,
    avgExtraPtsFouling: 4.8,
    avgExtraPtsLeading: 4.5,
  },
  "James Madison Dukes": {
    timesFouling: 5,
    timesLeading: 4,
    totalGames: 9,
    avgStartClock: 116.2,
    avgDeficit: 7.2,
    avgExtraPtsFouling: 4.9,
    avgExtraPtsLeading: 4.3,
  },
  "Samford Bulldogs": {
    timesFouling: 4,
    timesLeading: 5,
    totalGames: 9,
    avgStartClock: 110.2,
    avgDeficit: 7.5,
    avgExtraPtsFouling: 4.4,
    avgExtraPtsLeading: 3.4,
  },
  "Texas State Bobcats": {
    timesFouling: 4,
    timesLeading: 5,
    totalGames: 9,
    avgStartClock: 111.0,
    avgDeficit: 3.0,
    avgExtraPtsFouling: 7.0,
    avgExtraPtsLeading: 8.2,
  },
  "Campbell Fighting Camels": {
    timesFouling: 5,
    timesLeading: 4,
    totalGames: 9,
    avgStartClock: 112.4,
    avgDeficit: 4.4,
    avgExtraPtsFouling: 4.0,
    avgExtraPtsLeading: 4.2,
  },
  "Colorado State Rams": {
    timesFouling: 6,
    timesLeading: 3,
    totalGames: 9,
    avgStartClock: 102.8,
    avgDeficit: 5.7,
    avgExtraPtsFouling: 5.3,
    avgExtraPtsLeading: 4.0,
  },
  "App State Mountaineers": {
    timesFouling: 6,
    timesLeading: 3,
    totalGames: 9,
    avgStartClock: 109.0,
    avgDeficit: 7.0,
    avgExtraPtsFouling: 10.4,
    avgExtraPtsLeading: 4.5,
  },
  "Long Island University Sharks": {
    timesFouling: 3,
    timesLeading: 6,
    totalGames: 9,
    avgStartClock: 104.3,
    avgDeficit: 4.7,
    avgExtraPtsFouling: 3.0,
    avgExtraPtsLeading: 5.0,
  },
  "Washington Huskies": {
    timesFouling: 4,
    timesLeading: 4,
    totalGames: 8,
    avgStartClock: 100.0,
    avgDeficit: 6.5,
    avgExtraPtsFouling: 4.8,
    avgExtraPtsLeading: 4.3,
  },
  "Mississippi State Bulldogs": {
    timesFouling: 3,
    timesLeading: 5,
    totalGames: 8,
    avgStartClock: 110.7,
    avgDeficit: 2.3,
    avgExtraPtsFouling: 3.7,
    avgExtraPtsLeading: 2.7,
  },
  "Texas A&M Aggies": {
    timesFouling: 3,
    timesLeading: 5,
    totalGames: 8,
    avgStartClock: 112.7,
    avgDeficit: 6.3,
    avgExtraPtsFouling: 2.2,
    avgExtraPtsLeading: 8.1,
  },
  "Illinois State Redbirds": {
    timesFouling: 4,
    timesLeading: 4,
    totalGames: 8,
    avgStartClock: 114.8,
    avgDeficit: 2.8,
    avgExtraPtsFouling: 4.1,
    avgExtraPtsLeading: 6.6,
  },
  "George Mason Patriots": {
    timesFouling: 0,
    timesLeading: 8,
    totalGames: 8,
    avgStartClock: 0.0,
    avgDeficit: 0.0,
    avgExtraPtsFouling: 0.0,
    avgExtraPtsLeading: 8.1,
  },
  "Hampton Pirates": {
    timesFouling: 5,
    timesLeading: 3,
    totalGames: 8,
    avgStartClock: 111.8,
    avgDeficit: 5.8,
    avgExtraPtsFouling: 9.6,
    avgExtraPtsLeading: 7.9,
  },
  "Drexel Dragons": {
    timesFouling: 4,
    timesLeading: 4,
    totalGames: 8,
    avgStartClock: 117.8,
    avgDeficit: 5.2,
    avgExtraPtsFouling: 8.2,
    avgExtraPtsLeading: 6.8,
  },
  "Boston College Eagles": {
    timesFouling: 3,
    timesLeading: 5,
    totalGames: 8,
    avgStartClock: 113.7,
    avgDeficit: 7.7,
    avgExtraPtsFouling: 5.8,
    avgExtraPtsLeading: 6.2,
  },
  "Niagara Purple Eagles": {
    timesFouling: 6,
    timesLeading: 2,
    totalGames: 8,
    avgStartClock: 113.3,
    avgDeficit: 6.0,
    avgExtraPtsFouling: 11.4,
    avgExtraPtsLeading: 6.5,
  },
  "New Orleans Privateers": {
    timesFouling: 5,
    timesLeading: 3,
    totalGames: 8,
    avgStartClock: 112.8,
    avgDeficit: 5.6,
    avgExtraPtsFouling: 7.1,
    avgExtraPtsLeading: 6.1,
  },
  "Long Beach State Beach": {
    timesFouling: 5,
    timesLeading: 3,
    totalGames: 8,
    avgStartClock: 110.6,
    avgDeficit: 4.8,
    avgExtraPtsFouling: 9.0,
    avgExtraPtsLeading: 6.6,
  },
  "Southern Indiana Screaming Eagles": {
    timesFouling: 6,
    timesLeading: 2,
    totalGames: 8,
    avgStartClock: 114.0,
    avgDeficit: 6.7,
    avgExtraPtsFouling: 5.3,
    avgExtraPtsLeading: 8.4,
  },
  "Mercyhurst Lakers": {
    timesFouling: 6,
    timesLeading: 2,
    totalGames: 8,
    avgStartClock: 109.7,
    avgDeficit: 2.8,
    avgExtraPtsFouling: 6.0,
    avgExtraPtsLeading: 9.5,
  },
  "Southern Miss Golden Eagles": {
    timesFouling: 5,
    timesLeading: 3,
    totalGames: 8,
    avgStartClock: 116.2,
    avgDeficit: 6.2,
    avgExtraPtsFouling: 13.5,
    avgExtraPtsLeading: 15.5,
  },
  "Lehigh Mountain Hawks": {
    timesFouling: 7,
    timesLeading: 1,
    totalGames: 8,
    avgStartClock: 108.1,
    avgDeficit: 2.1,
    avgExtraPtsFouling: 5.4,
    avgExtraPtsLeading: 16.8,
  },
  "Georgetown Hoyas": {
    timesFouling: 5,
    timesLeading: 3,
    totalGames: 8,
    avgStartClock: 104.8,
    avgDeficit: 4.8,
    avgExtraPtsFouling: 4.4,
    avgExtraPtsLeading: 2.4,
  },
  "Toledo Rockets": {
    timesFouling: 4,
    timesLeading: 4,
    totalGames: 8,
    avgStartClock: 94.2,
    avgDeficit: 5.5,
    avgExtraPtsFouling: 7.2,
    avgExtraPtsLeading: 5.4,
  },
  "East Carolina Pirates": {
    timesFouling: 6,
    timesLeading: 2,
    totalGames: 8,
    avgStartClock: 113.3,
    avgDeficit: 4.3,
    avgExtraPtsFouling: 7.3,
    avgExtraPtsLeading: 10.5,
  },
  "East Texas A&M Lions": {
    timesFouling: 5,
    timesLeading: 3,
    totalGames: 8,
    avgStartClock: 97.6,
    avgDeficit: 6.8,
    avgExtraPtsFouling: 7.9,
    avgExtraPtsLeading: 3.3,
  },
  "Georgia Tech Yellow Jackets": {
    timesFouling: 6,
    timesLeading: 2,
    totalGames: 8,
    avgStartClock: 112.8,
    avgDeficit: 6.8,
    avgExtraPtsFouling: 4.7,
    avgExtraPtsLeading: 4.1,
  },
  "Wichita State Shockers": {
    timesFouling: 7,
    timesLeading: 1,
    totalGames: 8,
    avgStartClock: 115.6,
    avgDeficit: 6.0,
    avgExtraPtsFouling: 2.9,
    avgExtraPtsLeading: 6.2,
  },
  "Minnesota Golden Gophers": {
    timesFouling: 4,
    timesLeading: 4,
    totalGames: 8,
    avgStartClock: 109.0,
    avgDeficit: 5.8,
    avgExtraPtsFouling: 5.5,
    avgExtraPtsLeading: 7.3,
  },
  "Morehead State Eagles": {
    timesFouling: 5,
    timesLeading: 3,
    totalGames: 8,
    avgStartClock: 106.4,
    avgDeficit: 7.4,
    avgExtraPtsFouling: 6.4,
    avgExtraPtsLeading: 5.5,
  },
  "Alabama Crimson Tide": {
    timesFouling: 4,
    timesLeading: 4,
    totalGames: 8,
    avgStartClock: 111.8,
    avgDeficit: 6.0,
    avgExtraPtsFouling: 7.1,
    avgExtraPtsLeading: 6.8,
  },
  "Arkansas State Red Wolves": {
    timesFouling: 1,
    timesLeading: 7,
    totalGames: 8,
    avgStartClock: 103.0,
    avgDeficit: 2.0,
    avgExtraPtsFouling: 1.6,
    avgExtraPtsLeading: 6.8,
  },
  "New Mexico Lobos": {
    timesFouling: 4,
    timesLeading: 4,
    totalGames: 8,
    avgStartClock: 76.0,
    avgDeficit: 6.0,
    avgExtraPtsFouling: 1.9,
    avgExtraPtsLeading: 0.3,
  },
  "New Mexico State Aggies": {
    timesFouling: 4,
    timesLeading: 4,
    totalGames: 8,
    avgStartClock: 106.0,
    avgDeficit: 6.0,
    avgExtraPtsFouling: 3.5,
    avgExtraPtsLeading: 1.4,
  },
  "Northern Colorado Bears": {
    timesFouling: 4,
    timesLeading: 4,
    totalGames: 8,
    avgStartClock: 113.5,
    avgDeficit: 4.0,
    avgExtraPtsFouling: 4.1,
    avgExtraPtsLeading: 9.8,
  },
  "Le Moyne Dolphins": {
    timesFouling: 6,
    timesLeading: 2,
    totalGames: 8,
    avgStartClock: 109.3,
    avgDeficit: 7.5,
    avgExtraPtsFouling: 3.4,
    avgExtraPtsLeading: 9.7,
  },
  "UIC Flames": {
    timesFouling: 6,
    timesLeading: 2,
    totalGames: 8,
    avgStartClock: 104.8,
    avgDeficit: 5.0,
    avgExtraPtsFouling: 6.0,
    avgExtraPtsLeading: 14.8,
  },
  "Georgia Southern Eagles": {
    timesFouling: 4,
    timesLeading: 4,
    totalGames: 8,
    avgStartClock: 118.0,
    avgDeficit: 4.0,
    avgExtraPtsFouling: 4.7,
    avgExtraPtsLeading: 8.8,
  },
  "Ball State Cardinals": {
    timesFouling: 4,
    timesLeading: 4,
    totalGames: 8,
    avgStartClock: 111.2,
    avgDeficit: 8.8,
    avgExtraPtsFouling: 4.1,
    avgExtraPtsLeading: 5.2,
  },
  "Bellarmine Knights": {
    timesFouling: 6,
    timesLeading: 2,
    totalGames: 8,
    avgStartClock: 104.2,
    avgDeficit: 8.2,
    avgExtraPtsFouling: 9.0,
    avgExtraPtsLeading: 3.3,
  },
  "Montana Grizzlies": {
    timesFouling: 6,
    timesLeading: 2,
    totalGames: 8,
    avgStartClock: 114.3,
    avgDeficit: 5.0,
    avgExtraPtsFouling: 10.8,
    avgExtraPtsLeading: 10.4,
  },
  "Yale Bulldogs": {
    timesFouling: 2,
    timesLeading: 6,
    totalGames: 8,
    avgStartClock: 112.5,
    avgDeficit: 8.0,
    avgExtraPtsFouling: 3.2,
    avgExtraPtsLeading: 6.7,
  },
  "Fairfield Stags": {
    timesFouling: 5,
    timesLeading: 3,
    totalGames: 8,
    avgStartClock: 94.0,
    avgDeficit: 6.4,
    avgExtraPtsFouling: 6.6,
    avgExtraPtsLeading: 3.1,
  },
  "Utah Tech Trailblazers": {
    timesFouling: 6,
    timesLeading: 2,
    totalGames: 8,
    avgStartClock: 106.8,
    avgDeficit: 4.0,
    avgExtraPtsFouling: 4.7,
    avgExtraPtsLeading: 8.4,
  },
  "Maine Black Bears": {
    timesFouling: 7,
    timesLeading: 1,
    totalGames: 8,
    avgStartClock: 108.9,
    avgDeficit: 4.4,
    avgExtraPtsFouling: 6.6,
    avgExtraPtsLeading: 3.1,
  },
  "UC San Diego Tritons": {
    timesFouling: 3,
    timesLeading: 5,
    totalGames: 8,
    avgStartClock: 102.7,
    avgDeficit: 3.3,
    avgExtraPtsFouling: 5.0,
    avgExtraPtsLeading: 7.1,
  },
  "Idaho State Bengals": {
    timesFouling: 3,
    timesLeading: 5,
    totalGames: 8,
    avgStartClock: 112.3,
    avgDeficit: 6.3,
    avgExtraPtsFouling: 2.9,
    avgExtraPtsLeading: 5.9,
  },
  "Notre Dame Fighting Irish": {
    timesFouling: 3,
    timesLeading: 5,
    totalGames: 8,
    avgStartClock: 118.0,
    avgDeficit: 4.7,
    avgExtraPtsFouling: 11.7,
    avgExtraPtsLeading: 3.4,
  },
  "Southern Illinois Salukis": {
    timesFouling: 7,
    timesLeading: 1,
    totalGames: 8,
    avgStartClock: 110.1,
    avgDeficit: 4.4,
    avgExtraPtsFouling: 6.7,
    avgExtraPtsLeading: 10.4,
  },
  "Stetson Hatters": {
    timesFouling: 4,
    timesLeading: 4,
    totalGames: 8,
    avgStartClock: 113.0,
    avgDeficit: 5.0,
    avgExtraPtsFouling: 2.1,
    avgExtraPtsLeading: 8.3,
  },
  "Florida Gulf Coast Eagles": {
    timesFouling: 7,
    timesLeading: 1,
    totalGames: 8,
    avgStartClock: 109.7,
    avgDeficit: 6.3,
    avgExtraPtsFouling: 7.6,
    avgExtraPtsLeading: 20.3,
  },
  "Eastern Kentucky Colonels": {
    timesFouling: 6,
    timesLeading: 2,
    totalGames: 8,
    avgStartClock: 100.8,
    avgDeficit: 5.0,
    avgExtraPtsFouling: 4.8,
    avgExtraPtsLeading: 5.6,
  },
  "Rhode Island Rams": {
    timesFouling: 6,
    timesLeading: 2,
    totalGames: 8,
    avgStartClock: 98.0,
    avgDeficit: 7.3,
    avgExtraPtsFouling: 4.0,
    avgExtraPtsLeading: 1.8,
  },
  "Binghamton Bearcats": {
    timesFouling: 6,
    timesLeading: 2,
    totalGames: 8,
    avgStartClock: 102.8,
    avgDeficit: 5.5,
    avgExtraPtsFouling: 6.1,
    avgExtraPtsLeading: 3.3,
  },
  "California Golden Bears": {
    timesFouling: 3,
    timesLeading: 5,
    totalGames: 8,
    avgStartClock: 95.0,
    avgDeficit: 4.7,
    avgExtraPtsFouling: 5.3,
    avgExtraPtsLeading: 1.7,
  },
  "Seattle U Redhawks": {
    timesFouling: 3,
    timesLeading: 5,
    totalGames: 8,
    avgStartClock: 112.0,
    avgDeficit: 3.3,
    avgExtraPtsFouling: 8.1,
    avgExtraPtsLeading: 4.8,
  },
  "San Diego Toreros": {
    timesFouling: 5,
    timesLeading: 3,
    totalGames: 8,
    avgStartClock: 97.6,
    avgDeficit: 7.6,
    avgExtraPtsFouling: 6.5,
    avgExtraPtsLeading: 4.6,
  },
  "Ole Miss Rebels": {
    timesFouling: 2,
    timesLeading: 6,
    totalGames: 8,
    avgStartClock: 116.0,
    avgDeficit: 6.0,
    avgExtraPtsFouling: 4.8,
    avgExtraPtsLeading: 5.4,
  },
  "UC Davis Aggies": {
    timesFouling: 3,
    timesLeading: 5,
    totalGames: 8,
    avgStartClock: 99.7,
    avgDeficit: 5.0,
    avgExtraPtsFouling: 5.5,
    avgExtraPtsLeading: 6.6,
  },
  "Detroit Mercy Titans": {
    timesFouling: 5,
    timesLeading: 3,
    totalGames: 8,
    avgStartClock: 111.0,
    avgDeficit: 5.6,
    avgExtraPtsFouling: 8.4,
    avgExtraPtsLeading: 11.4,
  },
  "UNC Asheville Bulldogs": {
    timesFouling: 5,
    timesLeading: 3,
    totalGames: 8,
    avgStartClock: 98.6,
    avgDeficit: 5.6,
    avgExtraPtsFouling: 11.1,
    avgExtraPtsLeading: 6.3,
  },
  "Tennessee State Tigers": {
    timesFouling: 2,
    timesLeading: 6,
    totalGames: 8,
    avgStartClock: 106.5,
    avgDeficit: 3.0,
    avgExtraPtsFouling: 4.3,
    avgExtraPtsLeading: 6.5,
  },
  "Furman Paladins": {
    timesFouling: 3,
    timesLeading: 5,
    totalGames: 8,
    avgStartClock: 97.0,
    avgDeficit: 3.0,
    avgExtraPtsFouling: 9.7,
    avgExtraPtsLeading: 6.4,
  },
  "Dayton Flyers": {
    timesFouling: 3,
    timesLeading: 5,
    totalGames: 8,
    avgStartClock: 90.0,
    avgDeficit: 5.0,
    avgExtraPtsFouling: 3.1,
    avgExtraPtsLeading: 6.8,
  },
  "Chattanooga Mocs": {
    timesFouling: 5,
    timesLeading: 2,
    totalGames: 7,
    avgStartClock: 108.6,
    avgDeficit: 5.6,
    avgExtraPtsFouling: 5.4,
    avgExtraPtsLeading: 5.3,
  },
  "UTEP Miners": {
    timesFouling: 4,
    timesLeading: 3,
    totalGames: 7,
    avgStartClock: 86.0,
    avgDeficit: 4.8,
    avgExtraPtsFouling: 2.1,
    avgExtraPtsLeading: 3.5,
  },
  "Louisiana Tech Bulldogs": {
    timesFouling: 4,
    timesLeading: 3,
    totalGames: 7,
    avgStartClock: 110.8,
    avgDeficit: 6.0,
    avgExtraPtsFouling: 5.2,
    avgExtraPtsLeading: 3.2,
  },
  "Sam Houston Bearkats": {
    timesFouling: 4,
    timesLeading: 3,
    totalGames: 7,
    avgStartClock: 109.0,
    avgDeficit: 2.8,
    avgExtraPtsFouling: 5.8,
    avgExtraPtsLeading: 7.3,
  },
  "VCU Rams": {
    timesFouling: 5,
    timesLeading: 2,
    totalGames: 7,
    avgStartClock: 113.8,
    avgDeficit: 3.6,
    avgExtraPtsFouling: 4.0,
    avgExtraPtsLeading: 5.1,
  },
  "North Dakota State Bison": {
    timesFouling: 3,
    timesLeading: 4,
    totalGames: 7,
    avgStartClock: 101.7,
    avgDeficit: 4.7,
    avgExtraPtsFouling: 4.8,
    avgExtraPtsLeading: 5.7,
  },
  "Liberty Flames": {
    timesFouling: 2,
    timesLeading: 5,
    totalGames: 7,
    avgStartClock: 116.5,
    avgDeficit: 6.0,
    avgExtraPtsFouling: 3.8,
    avgExtraPtsLeading: 4.2,
  },
  "Boise State Broncos": {
    timesFouling: 3,
    timesLeading: 4,
    totalGames: 7,
    avgStartClock: 85.0,
    avgDeficit: 4.7,
    avgExtraPtsFouling: 4.4,
    avgExtraPtsLeading: 5.7,
  },
  "Presbyterian Blue Hose": {
    timesFouling: 3,
    timesLeading: 4,
    totalGames: 7,
    avgStartClock: 118.0,
    avgDeficit: 7.7,
    avgExtraPtsFouling: 8.7,
    avgExtraPtsLeading: 11.5,
  },
  "Youngstown State Penguins": {
    timesFouling: 4,
    timesLeading: 3,
    totalGames: 7,
    avgStartClock: 99.5,
    avgDeficit: 6.2,
    avgExtraPtsFouling: 6.4,
    avgExtraPtsLeading: 8.1,
  },
  "The Citadel Bulldogs": {
    timesFouling: 5,
    timesLeading: 2,
    totalGames: 7,
    avgStartClock: 111.2,
    avgDeficit: 6.6,
    avgExtraPtsFouling: 6.2,
    avgExtraPtsLeading: 0.8,
  },
  "St. Thomas-Minnesota Tommies": {
    timesFouling: 2,
    timesLeading: 5,
    totalGames: 7,
    avgStartClock: 109.0,
    avgDeficit: 6.0,
    avgExtraPtsFouling: 2.6,
    avgExtraPtsLeading: 6.4,
  },
  "UMBC Retrievers": {
    timesFouling: 4,
    timesLeading: 3,
    totalGames: 7,
    avgStartClock: 104.0,
    avgDeficit: 5.5,
    avgExtraPtsFouling: 2.5,
    avgExtraPtsLeading: 4.2,
  },
  "Cal State Fullerton Titans": {
    timesFouling: 6,
    timesLeading: 1,
    totalGames: 7,
    avgStartClock: 110.7,
    avgDeficit: 6.7,
    avgExtraPtsFouling: 14.0,
    avgExtraPtsLeading: 6.8,
  },
  "Northwestern Wildcats": {
    timesFouling: 7,
    timesLeading: 0,
    totalGames: 7,
    avgStartClock: 97.3,
    avgDeficit: 3.0,
    avgExtraPtsFouling: 6.2,
    avgExtraPtsLeading: 0.0,
  },
  "NC State Wolfpack": {
    timesFouling: 3,
    timesLeading: 4,
    totalGames: 7,
    avgStartClock: 110.7,
    avgDeficit: 8.3,
    avgExtraPtsFouling: 7.2,
    avgExtraPtsLeading: 2.1,
  },
  "North Texas Mean Green": {
    timesFouling: 2,
    timesLeading: 5,
    totalGames: 7,
    avgStartClock: 106.0,
    avgDeficit: 3.0,
    avgExtraPtsFouling: 8.6,
    avgExtraPtsLeading: 6.2,
  },
  "Tennessee Tech Golden Eagles": {
    timesFouling: 4,
    timesLeading: 3,
    totalGames: 7,
    avgStartClock: 113.0,
    avgDeficit: 4.5,
    avgExtraPtsFouling: 4.9,
    avgExtraPtsLeading: 9.6,
  },
  "South Alabama Jaguars": {
    timesFouling: 3,
    timesLeading: 4,
    totalGames: 7,
    avgStartClock: 99.7,
    avgDeficit: 3.3,
    avgExtraPtsFouling: 2.7,
    avgExtraPtsLeading: 4.3,
  },
  "North Florida Ospreys": {
    timesFouling: 7,
    timesLeading: 0,
    totalGames: 7,
    avgStartClock: 101.7,
    avgDeficit: 5.6,
    avgExtraPtsFouling: 5.9,
    avgExtraPtsLeading: 0.0,
  },
  "UCF Knights": {
    timesFouling: 1,
    timesLeading: 6,
    totalGames: 7,
    avgStartClock: 99.0,
    avgDeficit: 7.0,
    avgExtraPtsFouling: 11.7,
    avgExtraPtsLeading: 3.6,
  },
  "Florida Gators": {
    timesFouling: 5,
    timesLeading: 2,
    totalGames: 7,
    avgStartClock: 105.6,
    avgDeficit: 4.0,
    avgExtraPtsFouling: 8.5,
    avgExtraPtsLeading: 12.7,
  },
  "Saint Joseph's Hawks": {
    timesFouling: 5,
    timesLeading: 2,
    totalGames: 7,
    avgStartClock: 106.2,
    avgDeficit: 4.6,
    avgExtraPtsFouling: 3.2,
    avgExtraPtsLeading: 4.5,
  },
  "Pepperdine Waves": {
    timesFouling: 4,
    timesLeading: 3,
    totalGames: 7,
    avgStartClock: 113.0,
    avgDeficit: 6.5,
    avgExtraPtsFouling: 2.4,
    avgExtraPtsLeading: 4.5,
  },
  "Oakland Golden Grizzlies": {
    timesFouling: 4,
    timesLeading: 3,
    totalGames: 7,
    avgStartClock: 105.2,
    avgDeficit: 6.0,
    avgExtraPtsFouling: 7.1,
    avgExtraPtsLeading: 9.2,
  },
  "Seton Hall Pirates": {
    timesFouling: 6,
    timesLeading: 1,
    totalGames: 7,
    avgStartClock: 112.2,
    avgDeficit: 4.2,
    avgExtraPtsFouling: 4.9,
    avgExtraPtsLeading: 5.7,
  },
  "Lindenwood Lions": {
    timesFouling: 4,
    timesLeading: 3,
    totalGames: 7,
    avgStartClock: 109.2,
    avgDeficit: 3.0,
    avgExtraPtsFouling: 7.0,
    avgExtraPtsLeading: 3.3,
  },
  "Cincinnati Bearcats": {
    timesFouling: 5,
    timesLeading: 2,
    totalGames: 7,
    avgStartClock: 112.8,
    avgDeficit: 5.6,
    avgExtraPtsFouling: 7.0,
    avgExtraPtsLeading: 8.3,
  },
  "Auburn Tigers": {
    timesFouling: 2,
    timesLeading: 5,
    totalGames: 7,
    avgStartClock: 96.0,
    avgDeficit: 4.5,
    avgExtraPtsFouling: 6.8,
    avgExtraPtsLeading: 3.8,
  },
  "Davidson Wildcats": {
    timesFouling: 2,
    timesLeading: 5,
    totalGames: 7,
    avgStartClock: 101.5,
    avgDeficit: 4.5,
    avgExtraPtsFouling: 7.3,
    avgExtraPtsLeading: 7.8,
  },
  "Pennsylvania Quakers": {
    timesFouling: 2,
    timesLeading: 5,
    totalGames: 7,
    avgStartClock: 108.5,
    avgDeficit: 7.0,
    avgExtraPtsFouling: 4.7,
    avgExtraPtsLeading: 2.5,
  },
  "Missouri Tigers": {
    timesFouling: 2,
    timesLeading: 5,
    totalGames: 7,
    avgStartClock: 116.5,
    avgDeficit: 4.0,
    avgExtraPtsFouling: 3.2,
    avgExtraPtsLeading: 7.2,
  },
  "Mercer Bears": {
    timesFouling: 3,
    timesLeading: 4,
    totalGames: 7,
    avgStartClock: 111.7,
    avgDeficit: 8.3,
    avgExtraPtsFouling: 8.1,
    avgExtraPtsLeading: 7.5,
  },
  "West Georgia Wolves": {
    timesFouling: 1,
    timesLeading: 6,
    totalGames: 7,
    avgStartClock: 95.0,
    avgDeficit: 3.0,
    avgExtraPtsFouling: 7.2,
    avgExtraPtsLeading: 4.6,
  },
  "Fordham Rams": {
    timesFouling: 5,
    timesLeading: 2,
    totalGames: 7,
    avgStartClock: 109.8,
    avgDeficit: 7.2,
    avgExtraPtsFouling: 9.4,
    avgExtraPtsLeading: 7.5,
  },
  "Wyoming Cowboys": {
    timesFouling: 4,
    timesLeading: 3,
    totalGames: 7,
    avgStartClock: 113.0,
    avgDeficit: 4.0,
    avgExtraPtsFouling: 5.1,
    avgExtraPtsLeading: 10.5,
  },
  "Boston University Terriers": {
    timesFouling: 5,
    timesLeading: 2,
    totalGames: 7,
    avgStartClock: 114.6,
    avgDeficit: 5.4,
    avgExtraPtsFouling: 10.1,
    avgExtraPtsLeading: 5.5,
  },
  "Rice Owls": {
    timesFouling: 4,
    timesLeading: 3,
    totalGames: 7,
    avgStartClock: 105.8,
    avgDeficit: 6.2,
    avgExtraPtsFouling: 9.9,
    avgExtraPtsLeading: 7.3,
  },
  "Temple Owls": {
    timesFouling: 2,
    timesLeading: 5,
    totalGames: 7,
    avgStartClock: 115.5,
    avgDeficit: 5.0,
    avgExtraPtsFouling: 8.8,
    avgExtraPtsLeading: 9.4,
  },
  "Pacific Tigers": {
    timesFouling: 3,
    timesLeading: 4,
    totalGames: 7,
    avgStartClock: 108.0,
    avgDeficit: 4.3,
    avgExtraPtsFouling: 2.7,
    avgExtraPtsLeading: 11.6,
  },
  "Bowling Green Falcons": {
    timesFouling: 4,
    timesLeading: 3,
    totalGames: 7,
    avgStartClock: 103.5,
    avgDeficit: 7.8,
    avgExtraPtsFouling: 7.7,
    avgExtraPtsLeading: 9.5,
  },
  "Belmont Bruins": {
    timesFouling: 2,
    timesLeading: 5,
    totalGames: 7,
    avgStartClock: 103.5,
    avgDeficit: 2.0,
    avgExtraPtsFouling: 6.6,
    avgExtraPtsLeading: 11.7,
  },
  "UC Irvine Anteaters": {
    timesFouling: 3,
    timesLeading: 4,
    totalGames: 7,
    avgStartClock: 106.7,
    avgDeficit: 6.7,
    avgExtraPtsFouling: 3.7,
    avgExtraPtsLeading: 5.6,
  },
  "Delaware Blue Hens": {
    timesFouling: 5,
    timesLeading: 2,
    totalGames: 7,
    avgStartClock: 110.2,
    avgDeficit: 5.6,
    avgExtraPtsFouling: 3.2,
    avgExtraPtsLeading: 5.0,
  },
  "Eastern Michigan Eagles": {
    timesFouling: 2,
    timesLeading: 5,
    totalGames: 7,
    avgStartClock: 108.0,
    avgDeficit: 2.0,
    avgExtraPtsFouling: 3.9,
    avgExtraPtsLeading: 7.8,
  },
  "Virginia Tech Hokies": {
    timesFouling: 2,
    timesLeading: 5,
    totalGames: 7,
    avgStartClock: 109.5,
    avgDeficit: 6.0,
    avgExtraPtsFouling: 4.0,
    avgExtraPtsLeading: 5.0,
  },
  "William & Mary Tribe": {
    timesFouling: 3,
    timesLeading: 4,
    totalGames: 7,
    avgStartClock: 114.7,
    avgDeficit: 4.7,
    avgExtraPtsFouling: 5.9,
    avgExtraPtsLeading: 7.4,
  },
  "North Alabama Lions": {
    timesFouling: 3,
    timesLeading: 4,
    totalGames: 7,
    avgStartClock: 108.7,
    avgDeficit: 6.7,
    avgExtraPtsFouling: 5.4,
    avgExtraPtsLeading: 9.3,
  },
  "Monmouth Hawks": {
    timesFouling: 5,
    timesLeading: 2,
    totalGames: 7,
    avgStartClock: 110.8,
    avgDeficit: 3.4,
    avgExtraPtsFouling: 3.8,
    avgExtraPtsLeading: 1.3,
  },
  "Denver Pioneers": {
    timesFouling: 4,
    timesLeading: 3,
    totalGames: 7,
    avgStartClock: 112.5,
    avgDeficit: 5.0,
    avgExtraPtsFouling: 5.3,
    avgExtraPtsLeading: 2.2,
  },
  "Florida Atlantic Owls": {
    timesFouling: 3,
    timesLeading: 4,
    totalGames: 7,
    avgStartClock: 108.3,
    avgDeficit: 3.7,
    avgExtraPtsFouling: 3.6,
    avgExtraPtsLeading: 10.0,
  },
  "Purdue Fort Wayne Mastodons": {
    timesFouling: 2,
    timesLeading: 5,
    totalGames: 7,
    avgStartClock: 117.0,
    avgDeficit: 8.0,
    avgExtraPtsFouling: 13.6,
    avgExtraPtsLeading: 7.3,
  },
  "Canisius Golden Griffins": {
    timesFouling: 2,
    timesLeading: 5,
    totalGames: 7,
    avgStartClock: 105.5,
    avgDeficit: 7.0,
    avgExtraPtsFouling: 4.1,
    avgExtraPtsLeading: 6.9,
  },
  "Northern Kentucky Norse": {
    timesFouling: 4,
    timesLeading: 3,
    totalGames: 7,
    avgStartClock: 100.5,
    avgDeficit: 4.2,
    avgExtraPtsFouling: 1.9,
    avgExtraPtsLeading: 2.7,
  },
  "North Dakota Fighting Hawks": {
    timesFouling: 3,
    timesLeading: 4,
    totalGames: 7,
    avgStartClock: 114.7,
    avgDeficit: 4.3,
    avgExtraPtsFouling: 8.8,
    avgExtraPtsLeading: 3.0,
  },
  "Evansville Purple Aces": {
    timesFouling: 5,
    timesLeading: 2,
    totalGames: 7,
    avgStartClock: 100.2,
    avgDeficit: 4.0,
    avgExtraPtsFouling: 6.1,
    avgExtraPtsLeading: 5.7,
  },
  "Stonehill Skyhawks": {
    timesFouling: 3,
    timesLeading: 4,
    totalGames: 7,
    avgStartClock: 111.0,
    avgDeficit: 7.7,
    avgExtraPtsFouling: 3.5,
    avgExtraPtsLeading: 4.1,
  },
  "Western Kentucky Hilltoppers": {
    timesFouling: 4,
    timesLeading: 3,
    totalGames: 7,
    avgStartClock: 106.5,
    avgDeficit: 5.0,
    avgExtraPtsFouling: 7.4,
    avgExtraPtsLeading: 5.9,
  },
  "Nicholls Colonels": {
    timesFouling: 3,
    timesLeading: 4,
    totalGames: 7,
    avgStartClock: 109.0,
    avgDeficit: 4.3,
    avgExtraPtsFouling: 11.0,
    avgExtraPtsLeading: 4.6,
  },
  "Southeast Missouri State Redhawks": {
    timesFouling: 4,
    timesLeading: 2,
    totalGames: 6,
    avgStartClock: 111.8,
    avgDeficit: 5.8,
    avgExtraPtsFouling: 7.8,
    avgExtraPtsLeading: 2.1,
  },
  "South Carolina Gamecocks": {
    timesFouling: 4,
    timesLeading: 2,
    totalGames: 6,
    avgStartClock: 111.5,
    avgDeficit: 6.8,
    avgExtraPtsFouling: 6.8,
    avgExtraPtsLeading: 3.1,
  },
  "Tulane Green Wave": {
    timesFouling: 2,
    timesLeading: 4,
    totalGames: 6,
    avgStartClock: 86.0,
    avgDeficit: 9.0,
    avgExtraPtsFouling: 5.8,
    avgExtraPtsLeading: 6.9,
  },
  "Norfolk State Spartans": {
    timesFouling: 2,
    timesLeading: 4,
    totalGames: 6,
    avgStartClock: 119.0,
    avgDeficit: 4.0,
    avgExtraPtsFouling: 8.2,
    avgExtraPtsLeading: 3.7,
  },
  "Towson Tigers": {
    timesFouling: 2,
    timesLeading: 4,
    totalGames: 6,
    avgStartClock: 106.0,
    avgDeficit: 8.5,
    avgExtraPtsFouling: 5.5,
    avgExtraPtsLeading: 4.4,
  },
  "Houston Christian Huskies": {
    timesFouling: 3,
    timesLeading: 3,
    totalGames: 6,
    avgStartClock: 105.0,
    avgDeficit: 2.7,
    avgExtraPtsFouling: 5.9,
    avgExtraPtsLeading: 3.8,
  },
  "Middle Tennessee Blue Raiders": {
    timesFouling: 2,
    timesLeading: 4,
    totalGames: 6,
    avgStartClock: 114.5,
    avgDeficit: 4.0,
    avgExtraPtsFouling: 8.6,
    avgExtraPtsLeading: 3.0,
  },
  "Incarnate Word Cardinals": {
    timesFouling: 4,
    timesLeading: 2,
    totalGames: 6,
    avgStartClock: 115.8,
    avgDeficit: 4.5,
    avgExtraPtsFouling: 2.7,
    avgExtraPtsLeading: 13.0,
  },
  "Sacred Heart Pioneers": {
    timesFouling: 4,
    timesLeading: 2,
    totalGames: 6,
    avgStartClock: 93.5,
    avgDeficit: 7.0,
    avgExtraPtsFouling: 4.0,
    avgExtraPtsLeading: 8.8,
  },
  "Murray State Racers": {
    timesFouling: 2,
    timesLeading: 4,
    totalGames: 6,
    avgStartClock: 114.0,
    avgDeficit: 4.5,
    avgExtraPtsFouling: 3.0,
    avgExtraPtsLeading: 6.8,
  },
  "South Carolina Upstate Spartans": {
    timesFouling: 4,
    timesLeading: 2,
    totalGames: 6,
    avgStartClock: 109.0,
    avgDeficit: 6.5,
    avgExtraPtsFouling: 9.6,
    avgExtraPtsLeading: 9.3,
  },
  "Florida International Panthers": {
    timesFouling: 4,
    timesLeading: 2,
    totalGames: 6,
    avgStartClock: 114.8,
    avgDeficit: 4.8,
    avgExtraPtsFouling: 3.6,
    avgExtraPtsLeading: 7.4,
  },
  "Wake Forest Demon Deacons": {
    timesFouling: 4,
    timesLeading: 2,
    totalGames: 6,
    avgStartClock: 109.8,
    avgDeficit: 3.0,
    avgExtraPtsFouling: 7.0,
    avgExtraPtsLeading: 5.6,
  },
  "Butler Bulldogs": {
    timesFouling: 2,
    timesLeading: 4,
    totalGames: 6,
    avgStartClock: 107.5,
    avgDeficit: 6.5,
    avgExtraPtsFouling: 9.3,
    avgExtraPtsLeading: 4.2,
  },
  "Brown Bears": {
    timesFouling: 4,
    timesLeading: 2,
    totalGames: 6,
    avgStartClock: 106.0,
    avgDeficit: 5.8,
    avgExtraPtsFouling: 5.6,
    avgExtraPtsLeading: 3.0,
  },
  "North Carolina A&T Aggies": {
    timesFouling: 4,
    timesLeading: 2,
    totalGames: 6,
    avgStartClock: 110.0,
    avgDeficit: 5.2,
    avgExtraPtsFouling: 4.4,
    avgExtraPtsLeading: 4.1,
  },
  "Duke Blue Devils": {
    timesFouling: 0,
    timesLeading: 6,
    totalGames: 6,
    avgStartClock: 0.0,
    avgDeficit: 0.0,
    avgExtraPtsFouling: 0.0,
    avgExtraPtsLeading: 5.9,
  },
  "Saint Peter's Peacocks": {
    timesFouling: 2,
    timesLeading: 4,
    totalGames: 6,
    avgStartClock: 108.0,
    avgDeficit: 4.0,
    avgExtraPtsFouling: 7.6,
    avgExtraPtsLeading: 5.3,
  },
  "Oklahoma State Cowboys": {
    timesFouling: 1,
    timesLeading: 5,
    totalGames: 6,
    avgStartClock: 104.0,
    avgDeficit: 10.0,
    avgExtraPtsFouling: 1.0,
    avgExtraPtsLeading: 4.7,
  },
  "Creighton Bluejays": {
    timesFouling: 3,
    timesLeading: 3,
    totalGames: 6,
    avgStartClock: 112.3,
    avgDeficit: 5.3,
    avgExtraPtsFouling: 9.7,
    avgExtraPtsLeading: 4.0,
  },
  "VMI Keydets": {
    timesFouling: 5,
    timesLeading: 1,
    totalGames: 6,
    avgStartClock: 109.4,
    avgDeficit: 4.6,
    avgExtraPtsFouling: 5.0,
    avgExtraPtsLeading: 10.9,
  },
  "Grambling Tigers": {
    timesFouling: 3,
    timesLeading: 3,
    totalGames: 6,
    avgStartClock: 108.7,
    avgDeficit: 8.7,
    avgExtraPtsFouling: 9.2,
    avgExtraPtsLeading: 6.0,
  },
  "SMU Mustangs": {
    timesFouling: 3,
    timesLeading: 3,
    totalGames: 6,
    avgStartClock: 107.3,
    avgDeficit: 4.3,
    avgExtraPtsFouling: 4.5,
    avgExtraPtsLeading: 4.0,
  },
  "Ohio Bobcats": {
    timesFouling: 5,
    timesLeading: 1,
    totalGames: 6,
    avgStartClock: 112.8,
    avgDeficit: 4.8,
    avgExtraPtsFouling: 4.8,
    avgExtraPtsLeading: 6.3,
  },
  "Southern Utah Thunderbirds": {
    timesFouling: 5,
    timesLeading: 1,
    totalGames: 6,
    avgStartClock: 107.0,
    avgDeficit: 6.4,
    avgExtraPtsFouling: 4.0,
    avgExtraPtsLeading: 2.7,
  },
  "Abilene Christian Wildcats": {
    timesFouling: 1,
    timesLeading: 5,
    totalGames: 6,
    avgStartClock: 109.0,
    avgDeficit: 3.0,
    avgExtraPtsFouling: 4.8,
    avgExtraPtsLeading: 3.4,
  },
  "Maryland Terrapins": {
    timesFouling: 4,
    timesLeading: 2,
    totalGames: 6,
    avgStartClock: 96.2,
    avgDeficit: 9.5,
    avgExtraPtsFouling: 4.7,
    avgExtraPtsLeading: 7.7,
  },
  "Oral Roberts Golden Eagles": {
    timesFouling: 4,
    timesLeading: 2,
    totalGames: 6,
    avgStartClock: 116.0,
    avgDeficit: 7.5,
    avgExtraPtsFouling: 6.8,
    avgExtraPtsLeading: 7.2,
  },
  "Lamar Cardinals": {
    timesFouling: 3,
    timesLeading: 3,
    totalGames: 6,
    avgStartClock: 103.0,
    avgDeficit: 6.0,
    avgExtraPtsFouling: 3.7,
    avgExtraPtsLeading: 5.7,
  },
  "Duquesne Dukes": {
    timesFouling: 3,
    timesLeading: 3,
    totalGames: 6,
    avgStartClock: 112.3,
    avgDeficit: 2.3,
    avgExtraPtsFouling: 4.7,
    avgExtraPtsLeading: 7.7,
  },
  "Louisville Cardinals": {
    timesFouling: 3,
    timesLeading: 3,
    totalGames: 6,
    avgStartClock: 113.0,
    avgDeficit: 6.0,
    avgExtraPtsFouling: 2.7,
    avgExtraPtsLeading: 5.4,
  },
  "UT Martin Skyhawks": {
    timesFouling: 2,
    timesLeading: 4,
    totalGames: 6,
    avgStartClock: 98.0,
    avgDeficit: 1.5,
    avgExtraPtsFouling: 3.8,
    avgExtraPtsLeading: 3.8,
  },
  "Morgan State Bears": {
    timesFouling: 3,
    timesLeading: 3,
    totalGames: 6,
    avgStartClock: 107.3,
    avgDeficit: 7.0,
    avgExtraPtsFouling: 7.1,
    avgExtraPtsLeading: 9.8,
  },
  "Virginia Cavaliers": {
    timesFouling: 2,
    timesLeading: 4,
    totalGames: 6,
    avgStartClock: 117.5,
    avgDeficit: 7.0,
    avgExtraPtsFouling: 3.5,
    avgExtraPtsLeading: 4.8,
  },
  "Kansas Jayhawks": {
    timesFouling: 3,
    timesLeading: 3,
    totalGames: 6,
    avgStartClock: 98.7,
    avgDeficit: 3.3,
    avgExtraPtsFouling: 2.7,
    avgExtraPtsLeading: 6.6,
  },
  "BYU Cougars": {
    timesFouling: 1,
    timesLeading: 5,
    totalGames: 6,
    avgStartClock: 120.0,
    avgDeficit: 7.0,
    avgExtraPtsFouling: 11.1,
    avgExtraPtsLeading: 4.0,
  },
  "American University Eagles": {
    timesFouling: 2,
    timesLeading: 4,
    totalGames: 6,
    avgStartClock: 119.0,
    avgDeficit: 8.0,
    avgExtraPtsFouling: 7.5,
    avgExtraPtsLeading: 3.3,
  },
  "Memphis Tigers": {
    timesFouling: 3,
    timesLeading: 3,
    totalGames: 6,
    avgStartClock: 112.7,
    avgDeficit: 5.7,
    avgExtraPtsFouling: 3.4,
    avgExtraPtsLeading: 7.6,
  },
  "Northern Arizona Lumberjacks": {
    timesFouling: 3,
    timesLeading: 3,
    totalGames: 6,
    avgStartClock: 106.0,
    avgDeficit: 4.7,
    avgExtraPtsFouling: 2.5,
    avgExtraPtsLeading: 3.1,
  },
  "Loyola Maryland Greyhounds": {
    timesFouling: 5,
    timesLeading: 1,
    totalGames: 6,
    avgStartClock: 110.8,
    avgDeficit: 4.4,
    avgExtraPtsFouling: 6.9,
    avgExtraPtsLeading: 2.8,
  },
  "Villanova Wildcats": {
    timesFouling: 3,
    timesLeading: 3,
    totalGames: 6,
    avgStartClock: 111.3,
    avgDeficit: 6.3,
    avgExtraPtsFouling: 4.0,
    avgExtraPtsLeading: 8.6,
  },
  "Arkansas Razorbacks": {
    timesFouling: 3,
    timesLeading: 3,
    totalGames: 6,
    avgStartClock: 105.7,
    avgDeficit: 5.7,
    avgExtraPtsFouling: 1.5,
    avgExtraPtsLeading: 3.0,
  },
  "Kansas State Wildcats": {
    timesFouling: 4,
    timesLeading: 2,
    totalGames: 6,
    avgStartClock: 107.5,
    avgDeficit: 5.5,
    avgExtraPtsFouling: 4.2,
    avgExtraPtsLeading: 4.5,
  },
  "Missouri State Bears": {
    timesFouling: 3,
    timesLeading: 3,
    totalGames: 6,
    avgStartClock: 109.0,
    avgDeficit: 4.7,
    avgExtraPtsFouling: 8.8,
    avgExtraPtsLeading: 3.3,
  },
  "Siena Saints": {
    timesFouling: 4,
    timesLeading: 2,
    totalGames: 6,
    avgStartClock: 109.8,
    avgDeficit: 4.2,
    avgExtraPtsFouling: 7.6,
    avgExtraPtsLeading: 3.5,
  },
  "Western Michigan Broncos": {
    timesFouling: 4,
    timesLeading: 2,
    totalGames: 6,
    avgStartClock: 87.5,
    avgDeficit: 5.0,
    avgExtraPtsFouling: 6.5,
    avgExtraPtsLeading: 9.2,
  },
  "George Washington Revolutionaries": {
    timesFouling: 5,
    timesLeading: 1,
    totalGames: 6,
    avgStartClock: 110.0,
    avgDeficit: 6.6,
    avgExtraPtsFouling: 9.2,
    avgExtraPtsLeading: 8.3,
  },
  "Kennesaw State Owls": {
    timesFouling: 3,
    timesLeading: 3,
    totalGames: 6,
    avgStartClock: 107.7,
    avgDeficit: 6.3,
    avgExtraPtsFouling: 4.1,
    avgExtraPtsLeading: 12.4,
  },
  "Saint Francis Red Flash": {
    timesFouling: 5,
    timesLeading: 1,
    totalGames: 6,
    avgStartClock: 112.2,
    avgDeficit: 6.6,
    avgExtraPtsFouling: 6.0,
    avgExtraPtsLeading: 8.0,
  },
  "UMass Lowell River Hawks": {
    timesFouling: 4,
    timesLeading: 2,
    totalGames: 6,
    avgStartClock: 107.0,
    avgDeficit: 5.5,
    avgExtraPtsFouling: 2.4,
    avgExtraPtsLeading: 1.5,
  },
  "New Haven Chargers": {
    timesFouling: 3,
    timesLeading: 3,
    totalGames: 6,
    avgStartClock: 111.7,
    avgDeficit: 3.3,
    avgExtraPtsFouling: 7.0,
    avgExtraPtsLeading: 4.1,
  },
  "Western Carolina Catamounts": {
    timesFouling: 3,
    timesLeading: 3,
    totalGames: 6,
    avgStartClock: 111.3,
    avgDeficit: 4.3,
    avgExtraPtsFouling: 1.2,
    avgExtraPtsLeading: 7.0,
  },
  "Loyola Marymount Lions": {
    timesFouling: 2,
    timesLeading: 3,
    totalGames: 5,
    avgStartClock: 109.5,
    avgDeficit: 2.5,
    avgExtraPtsFouling: 6.9,
    avgExtraPtsLeading: 1.7,
  },
  "Cornell Big Red": {
    timesFouling: 3,
    timesLeading: 2,
    totalGames: 5,
    avgStartClock: 88.7,
    avgDeficit: 4.7,
    avgExtraPtsFouling: 8.2,
    avgExtraPtsLeading: 6.9,
  },
  "Queens University Royals": {
    timesFouling: 0,
    timesLeading: 5,
    totalGames: 5,
    avgStartClock: 0.0,
    avgDeficit: 0.0,
    avgExtraPtsFouling: 0.0,
    avgExtraPtsLeading: 4.6,
  },
  "Oregon Ducks": {
    timesFouling: 3,
    timesLeading: 2,
    totalGames: 5,
    avgStartClock: 103.7,
    avgDeficit: 9.7,
    avgExtraPtsFouling: 2.9,
    avgExtraPtsLeading: 8.0,
  },
  "Eastern Illinois Panthers": {
    timesFouling: 1,
    timesLeading: 4,
    totalGames: 5,
    avgStartClock: 119.0,
    avgDeficit: 1.0,
    avgExtraPtsFouling: 7.4,
    avgExtraPtsLeading: 5.6,
  },
  "Texas Tech Red Raiders": {
    timesFouling: 3,
    timesLeading: 2,
    totalGames: 5,
    avgStartClock: 105.7,
    avgDeficit: 3.7,
    avgExtraPtsFouling: 5.4,
    avgExtraPtsLeading: 10.4,
  },
  "Alcorn State Braves": {
    timesFouling: 3,
    timesLeading: 2,
    totalGames: 5,
    avgStartClock: 108.7,
    avgDeficit: 3.7,
    avgExtraPtsFouling: 7.9,
    avgExtraPtsLeading: 6.4,
  },
  "UAB Blazers": {
    timesFouling: 2,
    timesLeading: 3,
    totalGames: 5,
    avgStartClock: 113.5,
    avgDeficit: 8.0,
    avgExtraPtsFouling: 10.4,
    avgExtraPtsLeading: 6.4,
  },
  "Gonzaga Bulldogs": {
    timesFouling: 0,
    timesLeading: 5,
    totalGames: 5,
    avgStartClock: 0.0,
    avgDeficit: 0.0,
    avgExtraPtsFouling: 0.0,
    avgExtraPtsLeading: 5.5,
  },
  "Milwaukee Panthers": {
    timesFouling: 2,
    timesLeading: 3,
    totalGames: 5,
    avgStartClock: 117.0,
    avgDeficit: 3.5,
    avgExtraPtsFouling: 3.4,
    avgExtraPtsLeading: 4.9,
  },
  "Illinois Fighting Illini": {
    timesFouling: 1,
    timesLeading: 4,
    totalGames: 5,
    avgStartClock: 101.0,
    avgDeficit: 3.0,
    avgExtraPtsFouling: 18.4,
    avgExtraPtsLeading: 5.5,
  },
  "Houston Cougars": {
    timesFouling: 1,
    timesLeading: 4,
    totalGames: 5,
    avgStartClock: 99.0,
    avgDeficit: 2.0,
    avgExtraPtsFouling: 13.5,
    avgExtraPtsLeading: 2.7,
  },
  "Utah State Aggies": {
    timesFouling: 1,
    timesLeading: 4,
    totalGames: 5,
    avgStartClock: 120.0,
    avgDeficit: 8.0,
    avgExtraPtsFouling: 0.1,
    avgExtraPtsLeading: 6.0,
  },
  "Stephen F. Austin Lumberjacks": {
    timesFouling: 2,
    timesLeading: 3,
    totalGames: 5,
    avgStartClock: 95.5,
    avgDeficit: 1.5,
    avgExtraPtsFouling: 3.1,
    avgExtraPtsLeading: 7.7,
  },
  "Baylor Bears": {
    timesFouling: 3,
    timesLeading: 2,
    totalGames: 5,
    avgStartClock: 117.0,
    avgDeficit: 5.7,
    avgExtraPtsFouling: 7.7,
    avgExtraPtsLeading: 5.3,
  },
  "South Carolina State Bulldogs": {
    timesFouling: 3,
    timesLeading: 2,
    totalGames: 5,
    avgStartClock: 114.0,
    avgDeficit: 7.3,
    avgExtraPtsFouling: 6.3,
    avgExtraPtsLeading: 10.9,
  },
  "USC Trojans": {
    timesFouling: 2,
    timesLeading: 3,
    totalGames: 5,
    avgStartClock: 112.5,
    avgDeficit: 3.5,
    avgExtraPtsFouling: 6.7,
    avgExtraPtsLeading: 5.4,
  },
  "Arizona State Sun Devils": {
    timesFouling: 2,
    timesLeading: 3,
    totalGames: 5,
    avgStartClock: 115.0,
    avgDeficit: 3.5,
    avgExtraPtsFouling: 5.3,
    avgExtraPtsLeading: 9.2,
  },
  "UNC Greensboro Spartans": {
    timesFouling: 4,
    timesLeading: 1,
    totalGames: 5,
    avgStartClock: 110.5,
    avgDeficit: 6.8,
    avgExtraPtsFouling: 7.2,
    avgExtraPtsLeading: 13.7,
  },
  "Wagner Seahawks": {
    timesFouling: 2,
    timesLeading: 3,
    totalGames: 5,
    avgStartClock: 108.0,
    avgDeficit: 6.0,
    avgExtraPtsFouling: 8.6,
    avgExtraPtsLeading: 6.3,
  },
  "Kansas City Roos": {
    timesFouling: 4,
    timesLeading: 1,
    totalGames: 5,
    avgStartClock: 107.2,
    avgDeficit: 7.0,
    avgExtraPtsFouling: 1.9,
    avgExtraPtsLeading: 1.4,
  },
  "La Salle Explorers": {
    timesFouling: 2,
    timesLeading: 3,
    totalGames: 5,
    avgStartClock: 111.0,
    avgDeficit: 5.0,
    avgExtraPtsFouling: 0.8,
    avgExtraPtsLeading: 7.8,
  },
  "UT Rio Grande Valley Vaqueros": {
    timesFouling: 2,
    timesLeading: 3,
    totalGames: 5,
    avgStartClock: 117.5,
    avgDeficit: 6.5,
    avgExtraPtsFouling: 3.7,
    avgExtraPtsLeading: 2.8,
  },
  "Jacksonville Dolphins": {
    timesFouling: 3,
    timesLeading: 2,
    totalGames: 5,
    avgStartClock: 112.3,
    avgDeficit: 4.0,
    avgExtraPtsFouling: 0.2,
    avgExtraPtsLeading: 2.1,
  },
  "Florida A&M Rattlers": {
    timesFouling: 1,
    timesLeading: 4,
    totalGames: 5,
    avgStartClock: 81.0,
    avgDeficit: 2.0,
    avgExtraPtsFouling: 0.3,
    avgExtraPtsLeading: 4.0,
  },
  "Santa Clara Broncos": {
    timesFouling: 2,
    timesLeading: 3,
    totalGames: 5,
    avgStartClock: 106.0,
    avgDeficit: 3.0,
    avgExtraPtsFouling: 2.2,
    avgExtraPtsLeading: 4.8,
  },
  "East Tennessee State Buccaneers": {
    timesFouling: 3,
    timesLeading: 2,
    totalGames: 5,
    avgStartClock: 108.0,
    avgDeficit: 3.7,
    avgExtraPtsFouling: 6.8,
    avgExtraPtsLeading: 5.6,
  },
  "Ohio State Buckeyes": {
    timesFouling: 3,
    timesLeading: 2,
    totalGames: 5,
    avgStartClock: 113.7,
    avgDeficit: 6.0,
    avgExtraPtsFouling: 7.1,
    avgExtraPtsLeading: 5.3,
  },
  "Central Arkansas Bears": {
    timesFouling: 4,
    timesLeading: 1,
    totalGames: 5,
    avgStartClock: 97.5,
    avgDeficit: 4.5,
    avgExtraPtsFouling: 1.9,
    avgExtraPtsLeading: 0.0,
  },
  "McNeese Cowboys": {
    timesFouling: 1,
    timesLeading: 4,
    totalGames: 5,
    avgStartClock: 114.0,
    avgDeficit: 3.0,
    avgExtraPtsFouling: 9.0,
    avgExtraPtsLeading: 4.9,
  },
  "Grand Canyon Lopes": {
    timesFouling: 3,
    timesLeading: 2,
    totalGames: 5,
    avgStartClock: 102.7,
    avgDeficit: 9.0,
    avgExtraPtsFouling: 8.6,
    avgExtraPtsLeading: 5.9,
  },
  "Navy Midshipmen": {
    timesFouling: 1,
    timesLeading: 4,
    totalGames: 5,
    avgStartClock: 115.0,
    avgDeficit: 5.0,
    avgExtraPtsFouling: 0.8,
    avgExtraPtsLeading: 12.4,
  },
  "Xavier Musketeers": {
    timesFouling: 2,
    timesLeading: 3,
    totalGames: 5,
    avgStartClock: 119.0,
    avgDeficit: 2.5,
    avgExtraPtsFouling: 4.8,
    avgExtraPtsLeading: 3.4,
  },
  "UConn Huskies": {
    timesFouling: 0,
    timesLeading: 5,
    totalGames: 5,
    avgStartClock: 0.0,
    avgDeficit: 0.0,
    avgExtraPtsFouling: 0.0,
    avgExtraPtsLeading: 8.8,
  },
  "Little Rock Trojans": {
    timesFouling: 1,
    timesLeading: 4,
    totalGames: 5,
    avgStartClock: 55.0,
    avgDeficit: 2.0,
    avgExtraPtsFouling: 5.4,
    avgExtraPtsLeading: 5.1,
  },
  "Holy Cross Crusaders": {
    timesFouling: 2,
    timesLeading: 3,
    totalGames: 5,
    avgStartClock: 111.0,
    avgDeficit: 5.0,
    avgExtraPtsFouling: 5.4,
    avgExtraPtsLeading: 5.2,
  },
  "Alabama State Hornets": {
    timesFouling: 4,
    timesLeading: 1,
    totalGames: 5,
    avgStartClock: 94.8,
    avgDeficit: 8.5,
    avgExtraPtsFouling: 2.0,
    avgExtraPtsLeading: 13.5,
  },
  "Quinnipiac Bobcats": {
    timesFouling: 2,
    timesLeading: 3,
    totalGames: 5,
    avgStartClock: 101.0,
    avgDeficit: 3.0,
    avgExtraPtsFouling: 7.4,
    avgExtraPtsLeading: 5.3,
  },
  "South Dakota State Jackrabbits": {
    timesFouling: 4,
    timesLeading: 1,
    totalGames: 5,
    avgStartClock: 99.0,
    avgDeficit: 7.0,
    avgExtraPtsFouling: 5.4,
    avgExtraPtsLeading: 9.8,
  },
  "Kentucky Wildcats": {
    timesFouling: 3,
    timesLeading: 2,
    totalGames: 5,
    avgStartClock: 112.0,
    avgDeficit: 3.0,
    avgExtraPtsFouling: 1.3,
    avgExtraPtsLeading: 1.4,
  },
  "UT Arlington Mavericks": {
    timesFouling: 1,
    timesLeading: 4,
    totalGames: 5,
    avgStartClock: 108.0,
    avgDeficit: 1.0,
    avgExtraPtsFouling: 5.0,
    avgExtraPtsLeading: 4.3,
  },
  "Central Connecticut Blue Devils": {
    timesFouling: 2,
    timesLeading: 3,
    totalGames: 5,
    avgStartClock: 101.0,
    avgDeficit: 6.0,
    avgExtraPtsFouling: 2.9,
    avgExtraPtsLeading: 10.8,
  },
  "Troy Trojans": {
    timesFouling: 2,
    timesLeading: 3,
    totalGames: 5,
    avgStartClock: 105.5,
    avgDeficit: 2.5,
    avgExtraPtsFouling: 6.1,
    avgExtraPtsLeading: 6.9,
  },
  "Harvard Crimson": {
    timesFouling: 3,
    timesLeading: 2,
    totalGames: 5,
    avgStartClock: 112.3,
    avgDeficit: 5.0,
    avgExtraPtsFouling: 4.0,
    avgExtraPtsLeading: 4.0,
  },
  "Rider Broncs": {
    timesFouling: 3,
    timesLeading: 2,
    totalGames: 5,
    avgStartClock: 106.0,
    avgDeficit: 4.3,
    avgExtraPtsFouling: 3.1,
    avgExtraPtsLeading: 4.1,
  },
  "Providence Friars": {
    timesFouling: 3,
    timesLeading: 2,
    totalGames: 5,
    avgStartClock: 108.0,
    avgDeficit: 5.7,
    avgExtraPtsFouling: 9.8,
    avgExtraPtsLeading: 7.8,
  },
  "Hawai'i Rainbow Warriors": {
    timesFouling: 1,
    timesLeading: 4,
    totalGames: 5,
    avgStartClock: 97.0,
    avgDeficit: 2.0,
    avgExtraPtsFouling: 2.8,
    avgExtraPtsLeading: 5.4,
  },
  "Jackson State Tigers": {
    timesFouling: 3,
    timesLeading: 2,
    totalGames: 5,
    avgStartClock: 87.7,
    avgDeficit: 5.7,
    avgExtraPtsFouling: 5.2,
    avgExtraPtsLeading: 2.0,
  },
  "UC Riverside Highlanders": {
    timesFouling: 2,
    timesLeading: 3,
    totalGames: 5,
    avgStartClock: 111.5,
    avgDeficit: 2.0,
    avgExtraPtsFouling: 7.1,
    avgExtraPtsLeading: 10.3,
  },
  "Tulsa Golden Hurricane": {
    timesFouling: 1,
    timesLeading: 4,
    totalGames: 5,
    avgStartClock: 96.0,
    avgDeficit: 3.0,
    avgExtraPtsFouling: 10.9,
    avgExtraPtsLeading: 6.6,
  },
  "UCLA Bruins": {
    timesFouling: 2,
    timesLeading: 3,
    totalGames: 5,
    avgStartClock: 104.5,
    avgDeficit: 9.0,
    avgExtraPtsFouling: 5.2,
    avgExtraPtsLeading: 2.3,
  },
  "Northwestern State Demons": {
    timesFouling: 3,
    timesLeading: 2,
    totalGames: 5,
    avgStartClock: 112.0,
    avgDeficit: 5.7,
    avgExtraPtsFouling: 3.0,
    avgExtraPtsLeading: 9.3,
  },
  "Tennessee Volunteers": {
    timesFouling: 2,
    timesLeading: 3,
    totalGames: 5,
    avgStartClock: 108.0,
    avgDeficit: 5.5,
    avgExtraPtsFouling: 3.8,
    avgExtraPtsLeading: 5.2,
  },
  "Columbia Lions": {
    timesFouling: 2,
    timesLeading: 3,
    totalGames: 5,
    avgStartClock: 119.0,
    avgDeficit: 2.0,
    avgExtraPtsFouling: 8.6,
    avgExtraPtsLeading: 13.7,
  },
  "Vanderbilt Commodores": {
    timesFouling: 0,
    timesLeading: 4,
    totalGames: 4,
    avgStartClock: 0.0,
    avgDeficit: 0.0,
    avgExtraPtsFouling: 0.0,
    avgExtraPtsLeading: 7.1,
  },
  "Indiana Hoosiers": {
    timesFouling: 2,
    timesLeading: 2,
    totalGames: 4,
    avgStartClock: 103.5,
    avgDeficit: 6.5,
    avgExtraPtsFouling: 7.3,
    avgExtraPtsLeading: 4.1,
  },
  "Northern Illinois Huskies": {
    timesFouling: 2,
    timesLeading: 2,
    totalGames: 4,
    avgStartClock: 113.5,
    avgDeficit: 5.5,
    avgExtraPtsFouling: 4.3,
    avgExtraPtsLeading: 0.0,
  },
  "Michigan State Spartans": {
    timesFouling: 1,
    timesLeading: 3,
    totalGames: 4,
    avgStartClock: 119.0,
    avgDeficit: 2.0,
    avgExtraPtsFouling: 12.3,
    avgExtraPtsLeading: 4.9,
  },
  "Central Michigan Chippewas": {
    timesFouling: 2,
    timesLeading: 2,
    totalGames: 4,
    avgStartClock: 85.5,
    avgDeficit: 6.5,
    avgExtraPtsFouling: 4.5,
    avgExtraPtsLeading: 3.3,
  },
  "Pittsburgh Panthers": {
    timesFouling: 4,
    timesLeading: 0,
    totalGames: 4,
    avgStartClock: 104.5,
    avgDeficit: 6.2,
    avgExtraPtsFouling: 7.4,
    avgExtraPtsLeading: 0.0,
  },
  "SE Louisiana Lions": {
    timesFouling: 3,
    timesLeading: 1,
    totalGames: 4,
    avgStartClock: 109.7,
    avgDeficit: 7.0,
    avgExtraPtsFouling: 6.5,
    avgExtraPtsLeading: 0.8,
  },
  "Delaware State Hornets": {
    timesFouling: 3,
    timesLeading: 1,
    totalGames: 4,
    avgStartClock: 113.0,
    avgDeficit: 2.7,
    avgExtraPtsFouling: 4.1,
    avgExtraPtsLeading: 11.4,
  },
  "Marist Red Foxes": {
    timesFouling: 0,
    timesLeading: 4,
    totalGames: 4,
    avgStartClock: 0.0,
    avgDeficit: 0.0,
    avgExtraPtsFouling: 0.0,
    avgExtraPtsLeading: 6.7,
  },
  "LSU Tigers": {
    timesFouling: 3,
    timesLeading: 1,
    totalGames: 4,
    avgStartClock: 114.3,
    avgDeficit: 4.3,
    avgExtraPtsFouling: 2.5,
    avgExtraPtsLeading: 7.4,
  },
  "Prairie View A&M Panthers": {
    timesFouling: 1,
    timesLeading: 3,
    totalGames: 4,
    avgStartClock: 111.0,
    avgDeficit: 7.0,
    avgExtraPtsFouling: 6.6,
    avgExtraPtsLeading: 1.5,
  },
  "Utah Valley Wolverines": {
    timesFouling: 1,
    timesLeading: 3,
    totalGames: 4,
    avgStartClock: 114.0,
    avgDeficit: 1.0,
    avgExtraPtsFouling: 2.8,
    avgExtraPtsLeading: 4.6,
  },
  "Purdue Boilermakers": {
    timesFouling: 0,
    timesLeading: 4,
    totalGames: 4,
    avgStartClock: 0.0,
    avgDeficit: 0.0,
    avgExtraPtsFouling: 0.0,
    avgExtraPtsLeading: 3.8,
  },
  "Miami (OH) RedHawks": {
    timesFouling: 0,
    timesLeading: 4,
    totalGames: 4,
    avgStartClock: 0.0,
    avgDeficit: 0.0,
    avgExtraPtsFouling: 0.0,
    avgExtraPtsLeading: 5.0,
  },
  "New Hampshire Wildcats": {
    timesFouling: 3,
    timesLeading: 1,
    totalGames: 4,
    avgStartClock: 99.3,
    avgDeficit: 6.3,
    avgExtraPtsFouling: 0.7,
    avgExtraPtsLeading: 4.8,
  },
  "Wisconsin Badgers": {
    timesFouling: 1,
    timesLeading: 3,
    totalGames: 4,
    avgStartClock: 106.0,
    avgDeficit: 10.0,
    avgExtraPtsFouling: 11.7,
    avgExtraPtsLeading: 4.8,
  },
  "Bryant Bulldogs": {
    timesFouling: 2,
    timesLeading: 2,
    totalGames: 4,
    avgStartClock: 115.0,
    avgDeficit: 7.0,
    avgExtraPtsFouling: 3.5,
    avgExtraPtsLeading: 1.8,
  },
  "Southern Jaguars": {
    timesFouling: 3,
    timesLeading: 1,
    totalGames: 4,
    avgStartClock: 116.7,
    avgDeficit: 3.3,
    avgExtraPtsFouling: 4.0,
    avgExtraPtsLeading: 0.0,
  },
  "Cleveland State Vikings": {
    timesFouling: 2,
    timesLeading: 2,
    totalGames: 4,
    avgStartClock: 108.0,
    avgDeficit: 4.5,
    avgExtraPtsFouling: 5.0,
    avgExtraPtsLeading: 8.3,
  },
  "Winthrop Eagles": {
    timesFouling: 3,
    timesLeading: 1,
    totalGames: 4,
    avgStartClock: 116.3,
    avgDeficit: 5.3,
    avgExtraPtsFouling: 8.8,
    avgExtraPtsLeading: 0.0,
  },
  "Texas Longhorns": {
    timesFouling: 2,
    timesLeading: 2,
    totalGames: 4,
    avgStartClock: 111.5,
    avgDeficit: 8.0,
    avgExtraPtsFouling: 2.5,
    avgExtraPtsLeading: 11.2,
  },
  "Chicago State Cougars": {
    timesFouling: 3,
    timesLeading: 1,
    totalGames: 4,
    avgStartClock: 106.7,
    avgDeficit: 4.3,
    avgExtraPtsFouling: 5.1,
    avgExtraPtsLeading: 14.5,
  },
  "Saint Mary's Gaels": {
    timesFouling: 2,
    timesLeading: 2,
    totalGames: 4,
    avgStartClock: 77.5,
    avgDeficit: 3.5,
    avgExtraPtsFouling: 6.4,
    avgExtraPtsLeading: 2.4,
  },
  "UNLV Rebels": {
    timesFouling: 2,
    timesLeading: 2,
    totalGames: 4,
    avgStartClock: 111.0,
    avgDeficit: 2.5,
    avgExtraPtsFouling: 5.4,
    avgExtraPtsLeading: 1.0,
  },
  "Arizona Wildcats": {
    timesFouling: 1,
    timesLeading: 3,
    totalGames: 4,
    avgStartClock: 107.0,
    avgDeficit: 2.0,
    avgExtraPtsFouling: 6.1,
    avgExtraPtsLeading: 8.4,
  },
  "North Carolina Central Eagles": {
    timesFouling: 2,
    timesLeading: 2,
    totalGames: 4,
    avgStartClock: 114.5,
    avgDeficit: 3.5,
    avgExtraPtsFouling: 2.4,
    avgExtraPtsLeading: 6.4,
  },
  "UTSA Roadrunners": {
    timesFouling: 3,
    timesLeading: 1,
    totalGames: 4,
    avgStartClock: 78.3,
    avgDeficit: 6.3,
    avgExtraPtsFouling: 3.0,
    avgExtraPtsLeading: 5.4,
  },
  "Marquette Golden Eagles": {
    timesFouling: 3,
    timesLeading: 1,
    totalGames: 4,
    avgStartClock: 109.3,
    avgDeficit: 6.3,
    avgExtraPtsFouling: 3.0,
    avgExtraPtsLeading: 2.8,
  },
  "Arkansas-Pine Bluff Golden Lions": {
    timesFouling: 3,
    timesLeading: 1,
    totalGames: 4,
    avgStartClock: 84.3,
    avgDeficit: 6.0,
    avgExtraPtsFouling: 10.3,
    avgExtraPtsLeading: 5.1,
  },
  "Tarleton State Texans": {
    timesFouling: 3,
    timesLeading: 1,
    totalGames: 4,
    avgStartClock: 114.3,
    avgDeficit: 4.3,
    avgExtraPtsFouling: 8.4,
    avgExtraPtsLeading: 7.4,
  },
  "St. John's Red Storm": {
    timesFouling: 2,
    timesLeading: 2,
    totalGames: 4,
    avgStartClock: 117.0,
    avgDeficit: 9.5,
    avgExtraPtsFouling: 1.6,
    avgExtraPtsLeading: 8.3,
  },
  "Nebraska Cornhuskers": {
    timesFouling: 0,
    timesLeading: 4,
    totalGames: 4,
    avgStartClock: 0.0,
    avgDeficit: 0.0,
    avgExtraPtsFouling: 0.0,
    avgExtraPtsLeading: 8.4,
  },
  "Iowa Hawkeyes": {
    timesFouling: 3,
    timesLeading: 1,
    totalGames: 4,
    avgStartClock: 111.0,
    avgDeficit: 4.3,
    avgExtraPtsFouling: 7.4,
    avgExtraPtsLeading: 0.0,
  },
  "Penn State Nittany Lions": {
    timesFouling: 1,
    timesLeading: 3,
    totalGames: 4,
    avgStartClock: 94.0,
    avgDeficit: 2.0,
    avgExtraPtsFouling: 6.5,
    avgExtraPtsLeading: 2.7,
  },
  "Lafayette Leopards": {
    timesFouling: 3,
    timesLeading: 1,
    totalGames: 4,
    avgStartClock: 113.7,
    avgDeficit: 4.7,
    avgExtraPtsFouling: 9.2,
    avgExtraPtsLeading: 0.6,
  },
  "Sacramento State Hornets": {
    timesFouling: 3,
    timesLeading: 1,
    totalGames: 4,
    avgStartClock: 107.7,
    avgDeficit: 6.3,
    avgExtraPtsFouling: 3.9,
    avgExtraPtsLeading: 2.1,
  },
  "Maryland Eastern Shore Hawks": {
    timesFouling: 2,
    timesLeading: 2,
    totalGames: 4,
    avgStartClock: 112.0,
    avgDeficit: 4.0,
    avgExtraPtsFouling: 5.5,
    avgExtraPtsLeading: 1.0,
  },
  "South Florida Bulls": {
    timesFouling: 2,
    timesLeading: 2,
    totalGames: 4,
    avgStartClock: 109.0,
    avgDeficit: 5.5,
    avgExtraPtsFouling: 4.9,
    avgExtraPtsLeading: 0.5,
  },
  "Rutgers Scarlet Knights": {
    timesFouling: 2,
    timesLeading: 2,
    totalGames: 4,
    avgStartClock: 108.5,
    avgDeficit: 7.0,
    avgExtraPtsFouling: 3.1,
    avgExtraPtsLeading: 6.5,
  },
  "Georgia State Panthers": {
    timesFouling: 2,
    timesLeading: 2,
    totalGames: 4,
    avgStartClock: 114.0,
    avgDeficit: 1.5,
    avgExtraPtsFouling: 9.4,
    avgExtraPtsLeading: 9.0,
  },
  "Georgia Bulldogs": {
    timesFouling: 1,
    timesLeading: 3,
    totalGames: 4,
    avgStartClock: 117.0,
    avgDeficit: 3.0,
    avgExtraPtsFouling: 9.2,
    avgExtraPtsLeading: 6.5,
  },
  "Bethune-Cookman Wildcats": {
    timesFouling: 2,
    timesLeading: 2,
    totalGames: 4,
    avgStartClock: 109.0,
    avgDeficit: 2.5,
    avgExtraPtsFouling: 3.1,
    avgExtraPtsLeading: 2.4,
  },
  "North Carolina Tar Heels": {
    timesFouling: 1,
    timesLeading: 3,
    totalGames: 4,
    avgStartClock: 116.0,
    avgDeficit: 6.0,
    avgExtraPtsFouling: 2.3,
    avgExtraPtsLeading: 6.5,
  },
  "Coppin State Eagles": {
    timesFouling: 3,
    timesLeading: 1,
    totalGames: 4,
    avgStartClock: 112.3,
    avgDeficit: 5.0,
    avgExtraPtsFouling: 5.5,
    avgExtraPtsLeading: 1.4,
  },
  "West Virginia Mountaineers": {
    timesFouling: 2,
    timesLeading: 2,
    totalGames: 4,
    avgStartClock: 107.5,
    avgDeficit: 1.5,
    avgExtraPtsFouling: 4.4,
    avgExtraPtsLeading: 5.4,
  },
  "High Point Panthers": {
    timesFouling: 1,
    timesLeading: 3,
    totalGames: 4,
    avgStartClock: 99.0,
    avgDeficit: 6.0,
    avgExtraPtsFouling: 1.4,
    avgExtraPtsLeading: 4.7,
  },
  "Michigan Wolverines": {
    timesFouling: 1,
    timesLeading: 2,
    totalGames: 3,
    avgStartClock: 120.0,
    avgDeficit: 4.0,
    avgExtraPtsFouling: 0.0,
    avgExtraPtsLeading: 4.8,
  },
  "Air Force Falcons": {
    timesFouling: 3,
    timesLeading: 0,
    totalGames: 3,
    avgStartClock: 102.0,
    avgDeficit: 9.7,
    avgExtraPtsFouling: 8.8,
    avgExtraPtsLeading: 0.0,
  },
  "Saint Louis Billikens": {
    timesFouling: 0,
    timesLeading: 3,
    totalGames: 3,
    avgStartClock: 0.0,
    avgDeficit: 0.0,
    avgExtraPtsFouling: 0.0,
    avgExtraPtsLeading: 3.2,
  },
  "Florida State Seminoles": {
    timesFouling: 2,
    timesLeading: 1,
    totalGames: 3,
    avgStartClock: 113.0,
    avgDeficit: 5.0,
    avgExtraPtsFouling: 10.9,
    avgExtraPtsLeading: 3.3,
  },
  "Texas A&M-Corpus Christi Islanders": {
    timesFouling: 2,
    timesLeading: 1,
    totalGames: 3,
    avgStartClock: 85.0,
    avgDeficit: 6.0,
    avgExtraPtsFouling: 5.1,
    avgExtraPtsLeading: 2.5,
  },
  "NJIT Highlanders": {
    timesFouling: 1,
    timesLeading: 2,
    totalGames: 3,
    avgStartClock: 119.0,
    avgDeficit: 4.0,
    avgExtraPtsFouling: 3.1,
    avgExtraPtsLeading: 4.9,
  },
  "UAlbany Great Danes": {
    timesFouling: 3,
    timesLeading: 0,
    totalGames: 3,
    avgStartClock: 109.7,
    avgDeficit: 5.7,
    avgExtraPtsFouling: 6.3,
    avgExtraPtsLeading: 0.0,
  },
  "Miami Hurricanes": {
    timesFouling: 1,
    timesLeading: 2,
    totalGames: 3,
    avgStartClock: 110.0,
    avgDeficit: 9.0,
    avgExtraPtsFouling: 5.1,
    avgExtraPtsLeading: 3.5,
  },
  "Texas Southern Tigers": {
    timesFouling: 2,
    timesLeading: 1,
    totalGames: 3,
    avgStartClock: 104.5,
    avgDeficit: 3.0,
    avgExtraPtsFouling: 4.0,
    avgExtraPtsLeading: 0.5,
  },
  "UL Monroe Warhawks": {
    timesFouling: 3,
    timesLeading: 0,
    totalGames: 3,
    avgStartClock: 117.3,
    avgDeficit: 4.3,
    avgExtraPtsFouling: 5.7,
    avgExtraPtsLeading: 0.0,
  },
  "South Dakota Coyotes": {
    timesFouling: 1,
    timesLeading: 2,
    totalGames: 3,
    avgStartClock: 112.0,
    avgDeficit: 8.0,
    avgExtraPtsFouling: 9.5,
    avgExtraPtsLeading: 4.6,
  },
  "Akron Zips": {
    timesFouling: 2,
    timesLeading: 1,
    totalGames: 3,
    avgStartClock: 109.5,
    avgDeficit: 2.5,
    avgExtraPtsFouling: 8.6,
    avgExtraPtsLeading: 5.3,
  },
  "Alabama A&M Bulldogs": {
    timesFouling: 0,
    timesLeading: 3,
    totalGames: 3,
    avgStartClock: 0.0,
    avgDeficit: 0.0,
    avgExtraPtsFouling: 0.0,
    avgExtraPtsLeading: 6.6,
  },
};

// Average baseline stats (for comparison)
export const BASELINE_STATS = {
  avgExtraPts: 5.8,
  avgStartClock: 107,  // seconds
  avgDeficit: 5.2,
};

/**
 * Determine team's foul game tendency
 */
export function getTeamTendency(data: TeamFoulGameData): 'early' | 'late' | 'normal' | 'unknown' {
  if (data.timesFouling < 3) return 'unknown';
  if (data.avgStartClock > 112) return 'early';
  if (data.avgStartClock < 95) return 'late';
  return 'normal';
}

/**
 * Get display-friendly tendency label
 */
export function getTendencyLabel(tendency: string): string {
  switch (tendency) {
    case 'early': return 'Fouls Early (~1:55)';
    case 'late': return 'Fouls Late (~1:30)';
    case 'normal': return 'Normal Timing';
    default: return '';
  }
}

/**
 * Check if team is high impact (adds more than baseline extra pts)
 */
export function isHighImpact(data: TeamFoulGameData): boolean {
  const avgImpact = (data.avgExtraPtsFouling * data.timesFouling +
                     data.avgExtraPtsLeading * data.timesLeading) /
                    Math.max(1, data.totalGames);
  return avgImpact > 7.5;  // 1.7+ above baseline
}

/**
 * Get team's foul game data by name (fuzzy match)
 */
export function getTeamData(teamName: string): TeamFoulGameData | null {
  // Direct match
  if (TEAM_FOUL_GAME_DATA[teamName]) {
    return TEAM_FOUL_GAME_DATA[teamName];
  }

  // Fuzzy match - check if team name contains or is contained by a key
  const normalizedInput = teamName.toLowerCase().trim();

  for (const [key, data] of Object.entries(TEAM_FOUL_GAME_DATA)) {
    const normalizedKey = key.toLowerCase();

    // Check various matching strategies
    if (normalizedKey.includes(normalizedInput) ||
        normalizedInput.includes(normalizedKey.split(' ')[0])) {
      return data;
    }

    // Match on first word (school name)
    const inputFirst = normalizedInput.split(' ')[0];
    const keyFirst = normalizedKey.split(' ')[0];
    if (inputFirst === keyFirst && inputFirst.length > 3) {
      return data;
    }
  }

  return null;
}

/**
 * Get matchup foul game analysis
 */
export function analyzeMatchup(homeTeam: string, awayTeam: string): {
  homeData: TeamFoulGameData | null;
  awayData: TeamFoulGameData | null;
  combinedImpact: number;
  warningLevel: 'high' | 'medium' | 'low' | 'none';
  homeInfo: string | null;
  awayInfo: string | null;
} {
  const homeData = getTeamData(homeTeam);
  const awayData = getTeamData(awayTeam);

  let combinedImpact = 0;
  let homeInfo: string | null = null;
  let awayInfo: string | null = null;

  if (homeData && homeData.totalGames >= 3) {
    const homeAvg = (homeData.avgExtraPtsFouling * homeData.timesFouling +
                     homeData.avgExtraPtsLeading * homeData.timesLeading) /
                    homeData.totalGames;
    combinedImpact += homeAvg - BASELINE_STATS.avgExtraPts;

    const tendency = getTeamTendency(homeData);
    if (tendency !== 'normal' && tendency !== 'unknown') {
      homeInfo = getTendencyLabel(tendency);
    }
    if (isHighImpact(homeData)) {
      homeInfo = `High impact (+${homeAvg.toFixed(1)} pts)`;
    }
  }

  if (awayData && awayData.totalGames >= 3) {
    const awayAvg = (awayData.avgExtraPtsFouling * awayData.timesFouling +
                     awayData.avgExtraPtsLeading * awayData.timesLeading) /
                    awayData.totalGames;
    combinedImpact += awayAvg - BASELINE_STATS.avgExtraPts;

    const tendency = getTeamTendency(awayData);
    if (tendency !== 'normal' && tendency !== 'unknown') {
      awayInfo = getTendencyLabel(tendency);
    }
    if (isHighImpact(awayData)) {
      awayInfo = `High impact (+${awayAvg.toFixed(1)} pts)`;
    }
  }

  // Determine warning level
  let warningLevel: 'high' | 'medium' | 'low' | 'none' = 'none';
  if (combinedImpact > 5) {
    warningLevel = 'high';
  } else if (combinedImpact > 2) {
    warningLevel = 'medium';
  } else if (combinedImpact > 0 || homeInfo || awayInfo) {
    warningLevel = 'low';
  }

  return {
    homeData,
    awayData,
    combinedImpact: Math.max(0, combinedImpact),
    warningLevel,
    homeInfo,
    awayInfo,
  };
}
